# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_wall_ceiling_control/CeilingAttachmentStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class CeilingAttachmentStatus(genpy.Message):
  _md5sum = "ee6fc76925906c4e79bd0785bd2ec2d9"
  _type = "px4_wall_ceiling_control/CeilingAttachmentStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

uint8 STATE_NORMAL_FLIGHT=0
uint8 STATE_CEILING_ARMED=1
uint8 STATE_APPROACH=2
uint8 STATE_ATTACH_CONTROL=3
uint8 STATE_SURFACE_HOLD=4
uint8 STATE_DETACH=5
uint8 STATE_RECOVERY_HOVER=6
uint8 STATE_FAULT=7

uint8 state
string state_name
bool enabled
bool acquire_request
bool keep_ownership
bool candidate_valid
bool range_fresh
bool odom_fresh
bool flight_state_fresh
bool attach_confirmed
bool distance_stable
bool fault_detected
bool detach_failed
bool integral_reset_request
bool wheel_stop_request
bool mechanism_release_requested
bool mechanism_release_confirmed
float32 ceiling_distance_raw_m
float32 ceiling_distance_filtered_m
float32 target_distance_m
float32 compression_m
float32 target_compression_m
# ROS/MAVROS ENU convention: positive z means upward/toward a horizontal ceiling.
float32 approach_velocity_z_enu_mps
# PX4 body FRD convention retained from the reference: negative z is upward thrust.
float32 thrust_body_z_normalized
bool attitude_setpoint_valid
geometry_msgs/Quaternion attitude_setpoint
uint32 fault_count
string reason

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  # Pseudo-constants
  STATE_NORMAL_FLIGHT = 0
  STATE_CEILING_ARMED = 1
  STATE_APPROACH = 2
  STATE_ATTACH_CONTROL = 3
  STATE_SURFACE_HOLD = 4
  STATE_DETACH = 5
  STATE_RECOVERY_HOVER = 6
  STATE_FAULT = 7

  __slots__ = ['header','state','state_name','enabled','acquire_request','keep_ownership','candidate_valid','range_fresh','odom_fresh','flight_state_fresh','attach_confirmed','distance_stable','fault_detected','detach_failed','integral_reset_request','wheel_stop_request','mechanism_release_requested','mechanism_release_confirmed','ceiling_distance_raw_m','ceiling_distance_filtered_m','target_distance_m','compression_m','target_compression_m','approach_velocity_z_enu_mps','thrust_body_z_normalized','attitude_setpoint_valid','attitude_setpoint','fault_count','reason']
  _slot_types = ['std_msgs/Header','uint8','string','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','float32','float32','float32','float32','float32','float32','float32','bool','geometry_msgs/Quaternion','uint32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,state,state_name,enabled,acquire_request,keep_ownership,candidate_valid,range_fresh,odom_fresh,flight_state_fresh,attach_confirmed,distance_stable,fault_detected,detach_failed,integral_reset_request,wheel_stop_request,mechanism_release_requested,mechanism_release_confirmed,ceiling_distance_raw_m,ceiling_distance_filtered_m,target_distance_m,compression_m,target_compression_m,approach_velocity_z_enu_mps,thrust_body_z_normalized,attitude_setpoint_valid,attitude_setpoint,fault_count,reason

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CeilingAttachmentStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.state is None:
        self.state = 0
      if self.state_name is None:
        self.state_name = ''
      if self.enabled is None:
        self.enabled = False
      if self.acquire_request is None:
        self.acquire_request = False
      if self.keep_ownership is None:
        self.keep_ownership = False
      if self.candidate_valid is None:
        self.candidate_valid = False
      if self.range_fresh is None:
        self.range_fresh = False
      if self.odom_fresh is None:
        self.odom_fresh = False
      if self.flight_state_fresh is None:
        self.flight_state_fresh = False
      if self.attach_confirmed is None:
        self.attach_confirmed = False
      if self.distance_stable is None:
        self.distance_stable = False
      if self.fault_detected is None:
        self.fault_detected = False
      if self.detach_failed is None:
        self.detach_failed = False
      if self.integral_reset_request is None:
        self.integral_reset_request = False
      if self.wheel_stop_request is None:
        self.wheel_stop_request = False
      if self.mechanism_release_requested is None:
        self.mechanism_release_requested = False
      if self.mechanism_release_confirmed is None:
        self.mechanism_release_confirmed = False
      if self.ceiling_distance_raw_m is None:
        self.ceiling_distance_raw_m = 0.
      if self.ceiling_distance_filtered_m is None:
        self.ceiling_distance_filtered_m = 0.
      if self.target_distance_m is None:
        self.target_distance_m = 0.
      if self.compression_m is None:
        self.compression_m = 0.
      if self.target_compression_m is None:
        self.target_compression_m = 0.
      if self.approach_velocity_z_enu_mps is None:
        self.approach_velocity_z_enu_mps = 0.
      if self.thrust_body_z_normalized is None:
        self.thrust_body_z_normalized = 0.
      if self.attitude_setpoint_valid is None:
        self.attitude_setpoint_valid = False
      if self.attitude_setpoint is None:
        self.attitude_setpoint = geometry_msgs.msg.Quaternion()
      if self.fault_count is None:
        self.fault_count = 0
      if self.reason is None:
        self.reason = ''
    else:
      self.header = std_msgs.msg.Header()
      self.state = 0
      self.state_name = ''
      self.enabled = False
      self.acquire_request = False
      self.keep_ownership = False
      self.candidate_valid = False
      self.range_fresh = False
      self.odom_fresh = False
      self.flight_state_fresh = False
      self.attach_confirmed = False
      self.distance_stable = False
      self.fault_detected = False
      self.detach_failed = False
      self.integral_reset_request = False
      self.wheel_stop_request = False
      self.mechanism_release_requested = False
      self.mechanism_release_confirmed = False
      self.ceiling_distance_raw_m = 0.
      self.ceiling_distance_filtered_m = 0.
      self.target_distance_m = 0.
      self.compression_m = 0.
      self.target_compression_m = 0.
      self.approach_velocity_z_enu_mps = 0.
      self.thrust_body_z_normalized = 0.
      self.attitude_setpoint_valid = False
      self.attitude_setpoint = geometry_msgs.msg.Quaternion()
      self.fault_count = 0
      self.reason = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.state
      buff.write(_get_struct_B().pack(_x))
      _x = self.state_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_15B7fB4dI().pack(_x.enabled, _x.acquire_request, _x.keep_ownership, _x.candidate_valid, _x.range_fresh, _x.odom_fresh, _x.flight_state_fresh, _x.attach_confirmed, _x.distance_stable, _x.fault_detected, _x.detach_failed, _x.integral_reset_request, _x.wheel_stop_request, _x.mechanism_release_requested, _x.mechanism_release_confirmed, _x.ceiling_distance_raw_m, _x.ceiling_distance_filtered_m, _x.target_distance_m, _x.compression_m, _x.target_compression_m, _x.approach_velocity_z_enu_mps, _x.thrust_body_z_normalized, _x.attitude_setpoint_valid, _x.attitude_setpoint.x, _x.attitude_setpoint.y, _x.attitude_setpoint.z, _x.attitude_setpoint.w, _x.fault_count))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.attitude_setpoint is None:
        self.attitude_setpoint = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.state,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.state_name = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.enabled, _x.acquire_request, _x.keep_ownership, _x.candidate_valid, _x.range_fresh, _x.odom_fresh, _x.flight_state_fresh, _x.attach_confirmed, _x.distance_stable, _x.fault_detected, _x.detach_failed, _x.integral_reset_request, _x.wheel_stop_request, _x.mechanism_release_requested, _x.mechanism_release_confirmed, _x.ceiling_distance_raw_m, _x.ceiling_distance_filtered_m, _x.target_distance_m, _x.compression_m, _x.target_compression_m, _x.approach_velocity_z_enu_mps, _x.thrust_body_z_normalized, _x.attitude_setpoint_valid, _x.attitude_setpoint.x, _x.attitude_setpoint.y, _x.attitude_setpoint.z, _x.attitude_setpoint.w, _x.fault_count,) = _get_struct_15B7fB4dI().unpack(str[start:end])
      self.enabled = bool(self.enabled)
      self.acquire_request = bool(self.acquire_request)
      self.keep_ownership = bool(self.keep_ownership)
      self.candidate_valid = bool(self.candidate_valid)
      self.range_fresh = bool(self.range_fresh)
      self.odom_fresh = bool(self.odom_fresh)
      self.flight_state_fresh = bool(self.flight_state_fresh)
      self.attach_confirmed = bool(self.attach_confirmed)
      self.distance_stable = bool(self.distance_stable)
      self.fault_detected = bool(self.fault_detected)
      self.detach_failed = bool(self.detach_failed)
      self.integral_reset_request = bool(self.integral_reset_request)
      self.wheel_stop_request = bool(self.wheel_stop_request)
      self.mechanism_release_requested = bool(self.mechanism_release_requested)
      self.mechanism_release_confirmed = bool(self.mechanism_release_confirmed)
      self.attitude_setpoint_valid = bool(self.attitude_setpoint_valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.state
      buff.write(_get_struct_B().pack(_x))
      _x = self.state_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_15B7fB4dI().pack(_x.enabled, _x.acquire_request, _x.keep_ownership, _x.candidate_valid, _x.range_fresh, _x.odom_fresh, _x.flight_state_fresh, _x.attach_confirmed, _x.distance_stable, _x.fault_detected, _x.detach_failed, _x.integral_reset_request, _x.wheel_stop_request, _x.mechanism_release_requested, _x.mechanism_release_confirmed, _x.ceiling_distance_raw_m, _x.ceiling_distance_filtered_m, _x.target_distance_m, _x.compression_m, _x.target_compression_m, _x.approach_velocity_z_enu_mps, _x.thrust_body_z_normalized, _x.attitude_setpoint_valid, _x.attitude_setpoint.x, _x.attitude_setpoint.y, _x.attitude_setpoint.z, _x.attitude_setpoint.w, _x.fault_count))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.attitude_setpoint is None:
        self.attitude_setpoint = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.state,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.state_name = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.enabled, _x.acquire_request, _x.keep_ownership, _x.candidate_valid, _x.range_fresh, _x.odom_fresh, _x.flight_state_fresh, _x.attach_confirmed, _x.distance_stable, _x.fault_detected, _x.detach_failed, _x.integral_reset_request, _x.wheel_stop_request, _x.mechanism_release_requested, _x.mechanism_release_confirmed, _x.ceiling_distance_raw_m, _x.ceiling_distance_filtered_m, _x.target_distance_m, _x.compression_m, _x.target_compression_m, _x.approach_velocity_z_enu_mps, _x.thrust_body_z_normalized, _x.attitude_setpoint_valid, _x.attitude_setpoint.x, _x.attitude_setpoint.y, _x.attitude_setpoint.z, _x.attitude_setpoint.w, _x.fault_count,) = _get_struct_15B7fB4dI().unpack(str[start:end])
      self.enabled = bool(self.enabled)
      self.acquire_request = bool(self.acquire_request)
      self.keep_ownership = bool(self.keep_ownership)
      self.candidate_valid = bool(self.candidate_valid)
      self.range_fresh = bool(self.range_fresh)
      self.odom_fresh = bool(self.odom_fresh)
      self.flight_state_fresh = bool(self.flight_state_fresh)
      self.attach_confirmed = bool(self.attach_confirmed)
      self.distance_stable = bool(self.distance_stable)
      self.fault_detected = bool(self.fault_detected)
      self.detach_failed = bool(self.detach_failed)
      self.integral_reset_request = bool(self.integral_reset_request)
      self.wheel_stop_request = bool(self.wheel_stop_request)
      self.mechanism_release_requested = bool(self.mechanism_release_requested)
      self.mechanism_release_confirmed = bool(self.mechanism_release_confirmed)
      self.attitude_setpoint_valid = bool(self.attitude_setpoint_valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_15B7fB4dI = None
def _get_struct_15B7fB4dI():
    global _struct_15B7fB4dI
    if _struct_15B7fB4dI is None:
        _struct_15B7fB4dI = struct.Struct("<15B7fB4dI")
    return _struct_15B7fB4dI
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
