# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_wall_ceiling_control/WallPerchStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class WallPerchStatus(genpy.Message):
  _md5sum = "14c66e7871a6c1f7a0bda70d194bcb80"
  _type = "px4_wall_ceiling_control/WallPerchStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

uint8 STATE_IDLE=0
uint8 STATE_FRONT_WALL_DETECT=1
uint8 STATE_STABILIZE_HOVER=2
uint8 STATE_SLOW_APPROACH=3
uint8 STATE_FLIP_TO_WALL=4
uint8 STATE_WALL_CAPTURE=5
uint8 STATE_WALL_HOLD=6
uint8 STATE_WALL_PIN=7
uint8 STATE_DETACH_ROTATE=8
uint8 STATE_RECOVER=9
uint8 STATE_EXIT=10
uint8 STATE_ABORT=11

uint8 state
string state_name
bool enabled
bool acquire_request
bool keep_ownership
bool candidate_valid
bool front_range_fresh
bool top_range_fresh
bool sensor_health_fresh
bool top_preflight_ready
bool odom_fresh
bool flight_state_fresh
bool front_ready
bool flip_ready
bool top_contact_ready
bool top_clear_ready
bool fault_detected
bool neutral_setpoint_requested
bool attitude_setpoint_valid
float32 front_distance_raw_m
float32 front_distance_filtered_m
float32 top_distance_raw_m
float32 top_distance_filtered_m
float32 progress
geometry_msgs/Quaternion attitude_setpoint
# MAVROS AttitudeTarget convention: positive normalized collective thrust.
float32 thrust_normalized
uint32 fault_count
string reason

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  # Pseudo-constants
  STATE_IDLE = 0
  STATE_FRONT_WALL_DETECT = 1
  STATE_STABILIZE_HOVER = 2
  STATE_SLOW_APPROACH = 3
  STATE_FLIP_TO_WALL = 4
  STATE_WALL_CAPTURE = 5
  STATE_WALL_HOLD = 6
  STATE_WALL_PIN = 7
  STATE_DETACH_ROTATE = 8
  STATE_RECOVER = 9
  STATE_EXIT = 10
  STATE_ABORT = 11

  __slots__ = ['header','state','state_name','enabled','acquire_request','keep_ownership','candidate_valid','front_range_fresh','top_range_fresh','sensor_health_fresh','top_preflight_ready','odom_fresh','flight_state_fresh','front_ready','flip_ready','top_contact_ready','top_clear_ready','fault_detected','neutral_setpoint_requested','attitude_setpoint_valid','front_distance_raw_m','front_distance_filtered_m','top_distance_raw_m','top_distance_filtered_m','progress','attitude_setpoint','thrust_normalized','fault_count','reason']
  _slot_types = ['std_msgs/Header','uint8','string','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','float32','float32','float32','float32','float32','geometry_msgs/Quaternion','float32','uint32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,state,state_name,enabled,acquire_request,keep_ownership,candidate_valid,front_range_fresh,top_range_fresh,sensor_health_fresh,top_preflight_ready,odom_fresh,flight_state_fresh,front_ready,flip_ready,top_contact_ready,top_clear_ready,fault_detected,neutral_setpoint_requested,attitude_setpoint_valid,front_distance_raw_m,front_distance_filtered_m,top_distance_raw_m,top_distance_filtered_m,progress,attitude_setpoint,thrust_normalized,fault_count,reason

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WallPerchStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.state is None:
        self.state = 0
      if self.state_name is None:
        self.state_name = ''
      if self.enabled is None:
        self.enabled = False
      if self.acquire_request is None:
        self.acquire_request = False
      if self.keep_ownership is None:
        self.keep_ownership = False
      if self.candidate_valid is None:
        self.candidate_valid = False
      if self.front_range_fresh is None:
        self.front_range_fresh = False
      if self.top_range_fresh is None:
        self.top_range_fresh = False
      if self.sensor_health_fresh is None:
        self.sensor_health_fresh = False
      if self.top_preflight_ready is None:
        self.top_preflight_ready = False
      if self.odom_fresh is None:
        self.odom_fresh = False
      if self.flight_state_fresh is None:
        self.flight_state_fresh = False
      if self.front_ready is None:
        self.front_ready = False
      if self.flip_ready is None:
        self.flip_ready = False
      if self.top_contact_ready is None:
        self.top_contact_ready = False
      if self.top_clear_ready is None:
        self.top_clear_ready = False
      if self.fault_detected is None:
        self.fault_detected = False
      if self.neutral_setpoint_requested is None:
        self.neutral_setpoint_requested = False
      if self.attitude_setpoint_valid is None:
        self.attitude_setpoint_valid = False
      if self.front_distance_raw_m is None:
        self.front_distance_raw_m = 0.
      if self.front_distance_filtered_m is None:
        self.front_distance_filtered_m = 0.
      if self.top_distance_raw_m is None:
        self.top_distance_raw_m = 0.
      if self.top_distance_filtered_m is None:
        self.top_distance_filtered_m = 0.
      if self.progress is None:
        self.progress = 0.
      if self.attitude_setpoint is None:
        self.attitude_setpoint = geometry_msgs.msg.Quaternion()
      if self.thrust_normalized is None:
        self.thrust_normalized = 0.
      if self.fault_count is None:
        self.fault_count = 0
      if self.reason is None:
        self.reason = ''
    else:
      self.header = std_msgs.msg.Header()
      self.state = 0
      self.state_name = ''
      self.enabled = False
      self.acquire_request = False
      self.keep_ownership = False
      self.candidate_valid = False
      self.front_range_fresh = False
      self.top_range_fresh = False
      self.sensor_health_fresh = False
      self.top_preflight_ready = False
      self.odom_fresh = False
      self.flight_state_fresh = False
      self.front_ready = False
      self.flip_ready = False
      self.top_contact_ready = False
      self.top_clear_ready = False
      self.fault_detected = False
      self.neutral_setpoint_requested = False
      self.attitude_setpoint_valid = False
      self.front_distance_raw_m = 0.
      self.front_distance_filtered_m = 0.
      self.top_distance_raw_m = 0.
      self.top_distance_filtered_m = 0.
      self.progress = 0.
      self.attitude_setpoint = geometry_msgs.msg.Quaternion()
      self.thrust_normalized = 0.
      self.fault_count = 0
      self.reason = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.state
      buff.write(_get_struct_B().pack(_x))
      _x = self.state_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_17B5f4dfI().pack(_x.enabled, _x.acquire_request, _x.keep_ownership, _x.candidate_valid, _x.front_range_fresh, _x.top_range_fresh, _x.sensor_health_fresh, _x.top_preflight_ready, _x.odom_fresh, _x.flight_state_fresh, _x.front_ready, _x.flip_ready, _x.top_contact_ready, _x.top_clear_ready, _x.fault_detected, _x.neutral_setpoint_requested, _x.attitude_setpoint_valid, _x.front_distance_raw_m, _x.front_distance_filtered_m, _x.top_distance_raw_m, _x.top_distance_filtered_m, _x.progress, _x.attitude_setpoint.x, _x.attitude_setpoint.y, _x.attitude_setpoint.z, _x.attitude_setpoint.w, _x.thrust_normalized, _x.fault_count))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.attitude_setpoint is None:
        self.attitude_setpoint = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.state,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.state_name = str[start:end]
      _x = self
      start = end
      end += 77
      (_x.enabled, _x.acquire_request, _x.keep_ownership, _x.candidate_valid, _x.front_range_fresh, _x.top_range_fresh, _x.sensor_health_fresh, _x.top_preflight_ready, _x.odom_fresh, _x.flight_state_fresh, _x.front_ready, _x.flip_ready, _x.top_contact_ready, _x.top_clear_ready, _x.fault_detected, _x.neutral_setpoint_requested, _x.attitude_setpoint_valid, _x.front_distance_raw_m, _x.front_distance_filtered_m, _x.top_distance_raw_m, _x.top_distance_filtered_m, _x.progress, _x.attitude_setpoint.x, _x.attitude_setpoint.y, _x.attitude_setpoint.z, _x.attitude_setpoint.w, _x.thrust_normalized, _x.fault_count,) = _get_struct_17B5f4dfI().unpack(str[start:end])
      self.enabled = bool(self.enabled)
      self.acquire_request = bool(self.acquire_request)
      self.keep_ownership = bool(self.keep_ownership)
      self.candidate_valid = bool(self.candidate_valid)
      self.front_range_fresh = bool(self.front_range_fresh)
      self.top_range_fresh = bool(self.top_range_fresh)
      self.sensor_health_fresh = bool(self.sensor_health_fresh)
      self.top_preflight_ready = bool(self.top_preflight_ready)
      self.odom_fresh = bool(self.odom_fresh)
      self.flight_state_fresh = bool(self.flight_state_fresh)
      self.front_ready = bool(self.front_ready)
      self.flip_ready = bool(self.flip_ready)
      self.top_contact_ready = bool(self.top_contact_ready)
      self.top_clear_ready = bool(self.top_clear_ready)
      self.fault_detected = bool(self.fault_detected)
      self.neutral_setpoint_requested = bool(self.neutral_setpoint_requested)
      self.attitude_setpoint_valid = bool(self.attitude_setpoint_valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.state
      buff.write(_get_struct_B().pack(_x))
      _x = self.state_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_17B5f4dfI().pack(_x.enabled, _x.acquire_request, _x.keep_ownership, _x.candidate_valid, _x.front_range_fresh, _x.top_range_fresh, _x.sensor_health_fresh, _x.top_preflight_ready, _x.odom_fresh, _x.flight_state_fresh, _x.front_ready, _x.flip_ready, _x.top_contact_ready, _x.top_clear_ready, _x.fault_detected, _x.neutral_setpoint_requested, _x.attitude_setpoint_valid, _x.front_distance_raw_m, _x.front_distance_filtered_m, _x.top_distance_raw_m, _x.top_distance_filtered_m, _x.progress, _x.attitude_setpoint.x, _x.attitude_setpoint.y, _x.attitude_setpoint.z, _x.attitude_setpoint.w, _x.thrust_normalized, _x.fault_count))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.attitude_setpoint is None:
        self.attitude_setpoint = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.state,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.state_name = str[start:end]
      _x = self
      start = end
      end += 77
      (_x.enabled, _x.acquire_request, _x.keep_ownership, _x.candidate_valid, _x.front_range_fresh, _x.top_range_fresh, _x.sensor_health_fresh, _x.top_preflight_ready, _x.odom_fresh, _x.flight_state_fresh, _x.front_ready, _x.flip_ready, _x.top_contact_ready, _x.top_clear_ready, _x.fault_detected, _x.neutral_setpoint_requested, _x.attitude_setpoint_valid, _x.front_distance_raw_m, _x.front_distance_filtered_m, _x.top_distance_raw_m, _x.top_distance_filtered_m, _x.progress, _x.attitude_setpoint.x, _x.attitude_setpoint.y, _x.attitude_setpoint.z, _x.attitude_setpoint.w, _x.thrust_normalized, _x.fault_count,) = _get_struct_17B5f4dfI().unpack(str[start:end])
      self.enabled = bool(self.enabled)
      self.acquire_request = bool(self.acquire_request)
      self.keep_ownership = bool(self.keep_ownership)
      self.candidate_valid = bool(self.candidate_valid)
      self.front_range_fresh = bool(self.front_range_fresh)
      self.top_range_fresh = bool(self.top_range_fresh)
      self.sensor_health_fresh = bool(self.sensor_health_fresh)
      self.top_preflight_ready = bool(self.top_preflight_ready)
      self.odom_fresh = bool(self.odom_fresh)
      self.flight_state_fresh = bool(self.flight_state_fresh)
      self.front_ready = bool(self.front_ready)
      self.flip_ready = bool(self.flip_ready)
      self.top_contact_ready = bool(self.top_contact_ready)
      self.top_clear_ready = bool(self.top_clear_ready)
      self.fault_detected = bool(self.fault_detected)
      self.neutral_setpoint_requested = bool(self.neutral_setpoint_requested)
      self.attitude_setpoint_valid = bool(self.attitude_setpoint_valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_17B5f4dfI = None
def _get_struct_17B5f4dfI():
    global _struct_17B5f4dfI
    if _struct_17B5f4dfI is None:
        _struct_17B5f4dfI = struct.Struct("<17B5f4dfI")
    return _struct_17B5f4dfI
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
