// Generated by gencpp from file px4_wall_ceiling_control/AttachmentControlCandidate.msg
// DO NOT EDIT!


#ifndef PX4_WALL_CEILING_CONTROL_MESSAGE_ATTACHMENTCONTROLCANDIDATE_H
#define PX4_WALL_CEILING_CONTROL_MESSAGE_ATTACHMENTCONTROLCANDIDATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>

namespace px4_wall_ceiling_control
{
template <class ContainerAllocator>
struct AttachmentControlCandidate_
{
  typedef AttachmentControlCandidate_<ContainerAllocator> Type;

  AttachmentControlCandidate_()
    : header()
    , source(0)
    , kind(0)
    , acquire_request(false)
    , keep_ownership(false)
    , valid(false)
    , velocity_z_enu_mps(0.0)
    , attitude_setpoint()
    , thrust_normalized(0.0)
    , reason()  {
    }
  AttachmentControlCandidate_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , source(0)
    , kind(0)
    , acquire_request(false)
    , keep_ownership(false)
    , valid(false)
    , velocity_z_enu_mps(0.0)
    , attitude_setpoint(_alloc)
    , thrust_normalized(0.0)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _source_type;
  _source_type source;

   typedef uint8_t _kind_type;
  _kind_type kind;

   typedef uint8_t _acquire_request_type;
  _acquire_request_type acquire_request;

   typedef uint8_t _keep_ownership_type;
  _keep_ownership_type keep_ownership;

   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef float _velocity_z_enu_mps_type;
  _velocity_z_enu_mps_type velocity_z_enu_mps;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _attitude_setpoint_type;
  _attitude_setpoint_type attitude_setpoint;

   typedef float _thrust_normalized_type;
  _thrust_normalized_type thrust_normalized;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SOURCE_NONE)
  #undef SOURCE_NONE
#endif
#if defined(_WIN32) && defined(SOURCE_CEILING)
  #undef SOURCE_CEILING
#endif
#if defined(_WIN32) && defined(SOURCE_WALL)
  #undef SOURCE_WALL
#endif
#if defined(_WIN32) && defined(KIND_NONE)
  #undef KIND_NONE
#endif
#if defined(_WIN32) && defined(KIND_VERTICAL_VELOCITY)
  #undef KIND_VERTICAL_VELOCITY
#endif
#if defined(_WIN32) && defined(KIND_ATTITUDE_THRUST)
  #undef KIND_ATTITUDE_THRUST
#endif

  enum {
    SOURCE_NONE = 0u,
    SOURCE_CEILING = 1u,
    SOURCE_WALL = 2u,
    KIND_NONE = 0u,
    KIND_VERTICAL_VELOCITY = 1u,
    KIND_ATTITUDE_THRUST = 2u,
  };


  typedef boost::shared_ptr< ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator> const> ConstPtr;

}; // struct AttachmentControlCandidate_

typedef ::px4_wall_ceiling_control::AttachmentControlCandidate_<std::allocator<void> > AttachmentControlCandidate;

typedef boost::shared_ptr< ::px4_wall_ceiling_control::AttachmentControlCandidate > AttachmentControlCandidatePtr;
typedef boost::shared_ptr< ::px4_wall_ceiling_control::AttachmentControlCandidate const> AttachmentControlCandidateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.source == rhs.source &&
    lhs.kind == rhs.kind &&
    lhs.acquire_request == rhs.acquire_request &&
    lhs.keep_ownership == rhs.keep_ownership &&
    lhs.valid == rhs.valid &&
    lhs.velocity_z_enu_mps == rhs.velocity_z_enu_mps &&
    lhs.attitude_setpoint == rhs.attitude_setpoint &&
    lhs.thrust_normalized == rhs.thrust_normalized &&
    lhs.reason == rhs.reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_wall_ceiling_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a60e02517b779e0ed9645ce45b1715de";
  }

  static const char* value(const ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa60e02517b779e0eULL;
  static const uint64_t static_value2 = 0xd9645ce45b1715deULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_wall_ceiling_control/AttachmentControlCandidate";
  }

  static const char* value(const ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 SOURCE_NONE=0\n"
"uint8 SOURCE_CEILING=1\n"
"uint8 SOURCE_WALL=2\n"
"\n"
"uint8 KIND_NONE=0\n"
"uint8 KIND_VERTICAL_VELOCITY=1\n"
"uint8 KIND_ATTITUDE_THRUST=2\n"
"\n"
"uint8 source\n"
"uint8 kind\n"
"bool acquire_request\n"
"bool keep_ownership\n"
"bool valid\n"
"\n"
"# ROS-side ENU world convention.\n"
"float32 velocity_z_enu_mps\n"
"# ROS-side ENU/FLU attitude convention; MAVROS performs PX4 conversion.\n"
"geometry_msgs/Quaternion attitude_setpoint\n"
"# Positive normalized collective thrust expected by mavros_msgs/AttitudeTarget.\n"
"float32 thrust_normalized\n"
"string reason\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.source);
      stream.next(m.kind);
      stream.next(m.acquire_request);
      stream.next(m.keep_ownership);
      stream.next(m.valid);
      stream.next(m.velocity_z_enu_mps);
      stream.next(m.attitude_setpoint);
      stream.next(m.thrust_normalized);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AttachmentControlCandidate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_wall_ceiling_control::AttachmentControlCandidate_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "source: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.source);
    s << indent << "kind: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.kind);
    s << indent << "acquire_request: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.acquire_request);
    s << indent << "keep_ownership: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.keep_ownership);
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    s << indent << "velocity_z_enu_mps: ";
    Printer<float>::stream(s, indent + "  ", v.velocity_z_enu_mps);
    s << indent << "attitude_setpoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.attitude_setpoint);
    s << indent << "thrust_normalized: ";
    Printer<float>::stream(s, indent + "  ", v.thrust_normalized);
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_WALL_CEILING_CONTROL_MESSAGE_ATTACHMENTCONTROLCANDIDATE_H
