// Generated by gencpp from file px4_wall_ceiling_control/AttachmentMechanismCommand.msg
// DO NOT EDIT!


#ifndef PX4_WALL_CEILING_CONTROL_MESSAGE_ATTACHMENTMECHANISMCOMMAND_H
#define PX4_WALL_CEILING_CONTROL_MESSAGE_ATTACHMENTMECHANISMCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace px4_wall_ceiling_control
{
template <class ContainerAllocator>
struct AttachmentMechanismCommand_
{
  typedef AttachmentMechanismCommand_<ContainerAllocator> Type;

  AttachmentMechanismCommand_()
    : header()
    , source(0)
    , action(0)
    , sequence(0)
    , reason()  {
    }
  AttachmentMechanismCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , source(0)
    , action(0)
    , sequence(0)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _source_type;
  _source_type source;

   typedef uint8_t _action_type;
  _action_type action;

   typedef uint32_t _sequence_type;
  _sequence_type sequence;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SOURCE_NONE)
  #undef SOURCE_NONE
#endif
#if defined(_WIN32) && defined(SOURCE_CEILING)
  #undef SOURCE_CEILING
#endif
#if defined(_WIN32) && defined(SOURCE_WALL)
  #undef SOURCE_WALL
#endif
#if defined(_WIN32) && defined(ACTION_NONE)
  #undef ACTION_NONE
#endif
#if defined(_WIN32) && defined(ACTION_HOLD)
  #undef ACTION_HOLD
#endif
#if defined(_WIN32) && defined(ACTION_RELEASE)
  #undef ACTION_RELEASE
#endif
#if defined(_WIN32) && defined(ACTION_STOP)
  #undef ACTION_STOP
#endif

  enum {
    SOURCE_NONE = 0u,
    SOURCE_CEILING = 1u,
    SOURCE_WALL = 2u,
    ACTION_NONE = 0u,
    ACTION_HOLD = 1u,
    ACTION_RELEASE = 2u,
    ACTION_STOP = 3u,
  };


  typedef boost::shared_ptr< ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator> const> ConstPtr;

}; // struct AttachmentMechanismCommand_

typedef ::px4_wall_ceiling_control::AttachmentMechanismCommand_<std::allocator<void> > AttachmentMechanismCommand;

typedef boost::shared_ptr< ::px4_wall_ceiling_control::AttachmentMechanismCommand > AttachmentMechanismCommandPtr;
typedef boost::shared_ptr< ::px4_wall_ceiling_control::AttachmentMechanismCommand const> AttachmentMechanismCommandConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.source == rhs.source &&
    lhs.action == rhs.action &&
    lhs.sequence == rhs.sequence &&
    lhs.reason == rhs.reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_wall_ceiling_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1666c47965aea3b85746e7a2abcbf85d";
  }

  static const char* value(const ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1666c47965aea3b8ULL;
  static const uint64_t static_value2 = 0x5746e7a2abcbf85dULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_wall_ceiling_control/AttachmentMechanismCommand";
  }

  static const char* value(const ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 SOURCE_NONE=0\n"
"uint8 SOURCE_CEILING=1\n"
"uint8 SOURCE_WALL=2\n"
"\n"
"uint8 ACTION_NONE=0\n"
"uint8 ACTION_HOLD=1\n"
"uint8 ACTION_RELEASE=2\n"
"uint8 ACTION_STOP=3\n"
"\n"
"uint8 source\n"
"uint8 action\n"
"uint32 sequence\n"
"string reason\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.source);
      stream.next(m.action);
      stream.next(m.sequence);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AttachmentMechanismCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_wall_ceiling_control::AttachmentMechanismCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "source: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.source);
    s << indent << "action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action);
    s << indent << "sequence: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.sequence);
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_WALL_CEILING_CONTROL_MESSAGE_ATTACHMENTMECHANISMCOMMAND_H
