// Generated by gencpp from file px4_wall_ceiling_control/BehaviorCommand.msg
// DO NOT EDIT!


#ifndef PX4_WALL_CEILING_CONTROL_MESSAGE_BEHAVIORCOMMAND_H
#define PX4_WALL_CEILING_CONTROL_MESSAGE_BEHAVIORCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace px4_wall_ceiling_control
{
template <class ContainerAllocator>
struct BehaviorCommand_
{
  typedef BehaviorCommand_<ContainerAllocator> Type;

  BehaviorCommand_()
    : header()
    , source(0)
    , state(0)
    , active(false)
    , target_distance_m(0.0)
    , max_speed_mps(0.0)
    , reason()  {
    }
  BehaviorCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , source(0)
    , state(0)
    , active(false)
    , target_distance_m(0.0)
    , max_speed_mps(0.0)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _source_type;
  _source_type source;

   typedef uint8_t _state_type;
  _state_type state;

   typedef uint8_t _active_type;
  _active_type active;

   typedef float _target_distance_m_type;
  _target_distance_m_type target_distance_m;

   typedef float _max_speed_mps_type;
  _max_speed_mps_type max_speed_mps;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SOURCE_NONE)
  #undef SOURCE_NONE
#endif
#if defined(_WIN32) && defined(SOURCE_CEILING)
  #undef SOURCE_CEILING
#endif
#if defined(_WIN32) && defined(SOURCE_WALL)
  #undef SOURCE_WALL
#endif
#if defined(_WIN32) && defined(STATE_DISABLED)
  #undef STATE_DISABLED
#endif
#if defined(_WIN32) && defined(STATE_APPROACH)
  #undef STATE_APPROACH
#endif
#if defined(_WIN32) && defined(STATE_TRACK)
  #undef STATE_TRACK
#endif
#if defined(_WIN32) && defined(STATE_RETREAT)
  #undef STATE_RETREAT
#endif
#if defined(_WIN32) && defined(STATE_FAULT)
  #undef STATE_FAULT
#endif

  enum {
    SOURCE_NONE = 0u,
    SOURCE_CEILING = 1u,
    SOURCE_WALL = 2u,
    STATE_DISABLED = 0u,
    STATE_APPROACH = 1u,
    STATE_TRACK = 2u,
    STATE_RETREAT = 3u,
    STATE_FAULT = 4u,
  };


  typedef boost::shared_ptr< ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator> const> ConstPtr;

}; // struct BehaviorCommand_

typedef ::px4_wall_ceiling_control::BehaviorCommand_<std::allocator<void> > BehaviorCommand;

typedef boost::shared_ptr< ::px4_wall_ceiling_control::BehaviorCommand > BehaviorCommandPtr;
typedef boost::shared_ptr< ::px4_wall_ceiling_control::BehaviorCommand const> BehaviorCommandConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.source == rhs.source &&
    lhs.state == rhs.state &&
    lhs.active == rhs.active &&
    lhs.target_distance_m == rhs.target_distance_m &&
    lhs.max_speed_mps == rhs.max_speed_mps &&
    lhs.reason == rhs.reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_wall_ceiling_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5b91608717c6c01656752aca3ecaa53";
  }

  static const char* value(const ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5b91608717c6c01ULL;
  static const uint64_t static_value2 = 0x656752aca3ecaa53ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_wall_ceiling_control/BehaviorCommand";
  }

  static const char* value(const ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 SOURCE_NONE=0\n"
"uint8 SOURCE_CEILING=1\n"
"uint8 SOURCE_WALL=2\n"
"\n"
"uint8 STATE_DISABLED=0\n"
"uint8 STATE_APPROACH=1\n"
"uint8 STATE_TRACK=2\n"
"uint8 STATE_RETREAT=3\n"
"uint8 STATE_FAULT=4\n"
"\n"
"uint8 source\n"
"uint8 state\n"
"bool active\n"
"float32 target_distance_m\n"
"float32 max_speed_mps\n"
"string reason\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.source);
      stream.next(m.state);
      stream.next(m.active);
      stream.next(m.target_distance_m);
      stream.next(m.max_speed_mps);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BehaviorCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_wall_ceiling_control::BehaviorCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "source: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.source);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.active);
    s << indent << "target_distance_m: ";
    Printer<float>::stream(s, indent + "  ", v.target_distance_m);
    s << indent << "max_speed_mps: ";
    Printer<float>::stream(s, indent + "  ", v.max_speed_mps);
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_WALL_CEILING_CONTROL_MESSAGE_BEHAVIORCOMMAND_H
