// Generated by gencpp from file px4_wall_ceiling_control/WallPerchStatus.msg
// DO NOT EDIT!


#ifndef PX4_WALL_CEILING_CONTROL_MESSAGE_WALLPERCHSTATUS_H
#define PX4_WALL_CEILING_CONTROL_MESSAGE_WALLPERCHSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>

namespace px4_wall_ceiling_control
{
template <class ContainerAllocator>
struct WallPerchStatus_
{
  typedef WallPerchStatus_<ContainerAllocator> Type;

  WallPerchStatus_()
    : header()
    , state(0)
    , state_name()
    , enabled(false)
    , acquire_request(false)
    , keep_ownership(false)
    , candidate_valid(false)
    , front_range_fresh(false)
    , top_range_fresh(false)
    , sensor_health_fresh(false)
    , top_preflight_ready(false)
    , odom_fresh(false)
    , flight_state_fresh(false)
    , front_ready(false)
    , flip_ready(false)
    , top_contact_ready(false)
    , top_clear_ready(false)
    , fault_detected(false)
    , neutral_setpoint_requested(false)
    , attitude_setpoint_valid(false)
    , front_distance_raw_m(0.0)
    , front_distance_filtered_m(0.0)
    , top_distance_raw_m(0.0)
    , top_distance_filtered_m(0.0)
    , progress(0.0)
    , attitude_setpoint()
    , thrust_normalized(0.0)
    , fault_count(0)
    , reason()  {
    }
  WallPerchStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)
    , state_name(_alloc)
    , enabled(false)
    , acquire_request(false)
    , keep_ownership(false)
    , candidate_valid(false)
    , front_range_fresh(false)
    , top_range_fresh(false)
    , sensor_health_fresh(false)
    , top_preflight_ready(false)
    , odom_fresh(false)
    , flight_state_fresh(false)
    , front_ready(false)
    , flip_ready(false)
    , top_contact_ready(false)
    , top_clear_ready(false)
    , fault_detected(false)
    , neutral_setpoint_requested(false)
    , attitude_setpoint_valid(false)
    , front_distance_raw_m(0.0)
    , front_distance_filtered_m(0.0)
    , top_distance_raw_m(0.0)
    , top_distance_filtered_m(0.0)
    , progress(0.0)
    , attitude_setpoint(_alloc)
    , thrust_normalized(0.0)
    , fault_count(0)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_name_type;
  _state_name_type state_name;

   typedef uint8_t _enabled_type;
  _enabled_type enabled;

   typedef uint8_t _acquire_request_type;
  _acquire_request_type acquire_request;

   typedef uint8_t _keep_ownership_type;
  _keep_ownership_type keep_ownership;

   typedef uint8_t _candidate_valid_type;
  _candidate_valid_type candidate_valid;

   typedef uint8_t _front_range_fresh_type;
  _front_range_fresh_type front_range_fresh;

   typedef uint8_t _top_range_fresh_type;
  _top_range_fresh_type top_range_fresh;

   typedef uint8_t _sensor_health_fresh_type;
  _sensor_health_fresh_type sensor_health_fresh;

   typedef uint8_t _top_preflight_ready_type;
  _top_preflight_ready_type top_preflight_ready;

   typedef uint8_t _odom_fresh_type;
  _odom_fresh_type odom_fresh;

   typedef uint8_t _flight_state_fresh_type;
  _flight_state_fresh_type flight_state_fresh;

   typedef uint8_t _front_ready_type;
  _front_ready_type front_ready;

   typedef uint8_t _flip_ready_type;
  _flip_ready_type flip_ready;

   typedef uint8_t _top_contact_ready_type;
  _top_contact_ready_type top_contact_ready;

   typedef uint8_t _top_clear_ready_type;
  _top_clear_ready_type top_clear_ready;

   typedef uint8_t _fault_detected_type;
  _fault_detected_type fault_detected;

   typedef uint8_t _neutral_setpoint_requested_type;
  _neutral_setpoint_requested_type neutral_setpoint_requested;

   typedef uint8_t _attitude_setpoint_valid_type;
  _attitude_setpoint_valid_type attitude_setpoint_valid;

   typedef float _front_distance_raw_m_type;
  _front_distance_raw_m_type front_distance_raw_m;

   typedef float _front_distance_filtered_m_type;
  _front_distance_filtered_m_type front_distance_filtered_m;

   typedef float _top_distance_raw_m_type;
  _top_distance_raw_m_type top_distance_raw_m;

   typedef float _top_distance_filtered_m_type;
  _top_distance_filtered_m_type top_distance_filtered_m;

   typedef float _progress_type;
  _progress_type progress;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _attitude_setpoint_type;
  _attitude_setpoint_type attitude_setpoint;

   typedef float _thrust_normalized_type;
  _thrust_normalized_type thrust_normalized;

   typedef uint32_t _fault_count_type;
  _fault_count_type fault_count;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STATE_IDLE)
  #undef STATE_IDLE
#endif
#if defined(_WIN32) && defined(STATE_FRONT_WALL_DETECT)
  #undef STATE_FRONT_WALL_DETECT
#endif
#if defined(_WIN32) && defined(STATE_STABILIZE_HOVER)
  #undef STATE_STABILIZE_HOVER
#endif
#if defined(_WIN32) && defined(STATE_SLOW_APPROACH)
  #undef STATE_SLOW_APPROACH
#endif
#if defined(_WIN32) && defined(STATE_FLIP_TO_WALL)
  #undef STATE_FLIP_TO_WALL
#endif
#if defined(_WIN32) && defined(STATE_WALL_CAPTURE)
  #undef STATE_WALL_CAPTURE
#endif
#if defined(_WIN32) && defined(STATE_WALL_HOLD)
  #undef STATE_WALL_HOLD
#endif
#if defined(_WIN32) && defined(STATE_WALL_PIN)
  #undef STATE_WALL_PIN
#endif
#if defined(_WIN32) && defined(STATE_DETACH_ROTATE)
  #undef STATE_DETACH_ROTATE
#endif
#if defined(_WIN32) && defined(STATE_RECOVER)
  #undef STATE_RECOVER
#endif
#if defined(_WIN32) && defined(STATE_EXIT)
  #undef STATE_EXIT
#endif
#if defined(_WIN32) && defined(STATE_ABORT)
  #undef STATE_ABORT
#endif

  enum {
    STATE_IDLE = 0u,
    STATE_FRONT_WALL_DETECT = 1u,
    STATE_STABILIZE_HOVER = 2u,
    STATE_SLOW_APPROACH = 3u,
    STATE_FLIP_TO_WALL = 4u,
    STATE_WALL_CAPTURE = 5u,
    STATE_WALL_HOLD = 6u,
    STATE_WALL_PIN = 7u,
    STATE_DETACH_ROTATE = 8u,
    STATE_RECOVER = 9u,
    STATE_EXIT = 10u,
    STATE_ABORT = 11u,
  };


  typedef boost::shared_ptr< ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator> const> ConstPtr;

}; // struct WallPerchStatus_

typedef ::px4_wall_ceiling_control::WallPerchStatus_<std::allocator<void> > WallPerchStatus;

typedef boost::shared_ptr< ::px4_wall_ceiling_control::WallPerchStatus > WallPerchStatusPtr;
typedef boost::shared_ptr< ::px4_wall_ceiling_control::WallPerchStatus const> WallPerchStatusConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state &&
    lhs.state_name == rhs.state_name &&
    lhs.enabled == rhs.enabled &&
    lhs.acquire_request == rhs.acquire_request &&
    lhs.keep_ownership == rhs.keep_ownership &&
    lhs.candidate_valid == rhs.candidate_valid &&
    lhs.front_range_fresh == rhs.front_range_fresh &&
    lhs.top_range_fresh == rhs.top_range_fresh &&
    lhs.sensor_health_fresh == rhs.sensor_health_fresh &&
    lhs.top_preflight_ready == rhs.top_preflight_ready &&
    lhs.odom_fresh == rhs.odom_fresh &&
    lhs.flight_state_fresh == rhs.flight_state_fresh &&
    lhs.front_ready == rhs.front_ready &&
    lhs.flip_ready == rhs.flip_ready &&
    lhs.top_contact_ready == rhs.top_contact_ready &&
    lhs.top_clear_ready == rhs.top_clear_ready &&
    lhs.fault_detected == rhs.fault_detected &&
    lhs.neutral_setpoint_requested == rhs.neutral_setpoint_requested &&
    lhs.attitude_setpoint_valid == rhs.attitude_setpoint_valid &&
    lhs.front_distance_raw_m == rhs.front_distance_raw_m &&
    lhs.front_distance_filtered_m == rhs.front_distance_filtered_m &&
    lhs.top_distance_raw_m == rhs.top_distance_raw_m &&
    lhs.top_distance_filtered_m == rhs.top_distance_filtered_m &&
    lhs.progress == rhs.progress &&
    lhs.attitude_setpoint == rhs.attitude_setpoint &&
    lhs.thrust_normalized == rhs.thrust_normalized &&
    lhs.fault_count == rhs.fault_count &&
    lhs.reason == rhs.reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_wall_ceiling_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14c66e7871a6c1f7a0bda70d194bcb80";
  }

  static const char* value(const ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14c66e7871a6c1f7ULL;
  static const uint64_t static_value2 = 0xa0bda70d194bcb80ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_wall_ceiling_control/WallPerchStatus";
  }

  static const char* value(const ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 STATE_IDLE=0\n"
"uint8 STATE_FRONT_WALL_DETECT=1\n"
"uint8 STATE_STABILIZE_HOVER=2\n"
"uint8 STATE_SLOW_APPROACH=3\n"
"uint8 STATE_FLIP_TO_WALL=4\n"
"uint8 STATE_WALL_CAPTURE=5\n"
"uint8 STATE_WALL_HOLD=6\n"
"uint8 STATE_WALL_PIN=7\n"
"uint8 STATE_DETACH_ROTATE=8\n"
"uint8 STATE_RECOVER=9\n"
"uint8 STATE_EXIT=10\n"
"uint8 STATE_ABORT=11\n"
"\n"
"uint8 state\n"
"string state_name\n"
"bool enabled\n"
"bool acquire_request\n"
"bool keep_ownership\n"
"bool candidate_valid\n"
"bool front_range_fresh\n"
"bool top_range_fresh\n"
"bool sensor_health_fresh\n"
"bool top_preflight_ready\n"
"bool odom_fresh\n"
"bool flight_state_fresh\n"
"bool front_ready\n"
"bool flip_ready\n"
"bool top_contact_ready\n"
"bool top_clear_ready\n"
"bool fault_detected\n"
"bool neutral_setpoint_requested\n"
"bool attitude_setpoint_valid\n"
"float32 front_distance_raw_m\n"
"float32 front_distance_filtered_m\n"
"float32 top_distance_raw_m\n"
"float32 top_distance_filtered_m\n"
"float32 progress\n"
"geometry_msgs/Quaternion attitude_setpoint\n"
"# MAVROS AttitudeTarget convention: positive normalized collective thrust.\n"
"float32 thrust_normalized\n"
"uint32 fault_count\n"
"string reason\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.state_name);
      stream.next(m.enabled);
      stream.next(m.acquire_request);
      stream.next(m.keep_ownership);
      stream.next(m.candidate_valid);
      stream.next(m.front_range_fresh);
      stream.next(m.top_range_fresh);
      stream.next(m.sensor_health_fresh);
      stream.next(m.top_preflight_ready);
      stream.next(m.odom_fresh);
      stream.next(m.flight_state_fresh);
      stream.next(m.front_ready);
      stream.next(m.flip_ready);
      stream.next(m.top_contact_ready);
      stream.next(m.top_clear_ready);
      stream.next(m.fault_detected);
      stream.next(m.neutral_setpoint_requested);
      stream.next(m.attitude_setpoint_valid);
      stream.next(m.front_distance_raw_m);
      stream.next(m.front_distance_filtered_m);
      stream.next(m.top_distance_raw_m);
      stream.next(m.top_distance_filtered_m);
      stream.next(m.progress);
      stream.next(m.attitude_setpoint);
      stream.next(m.thrust_normalized);
      stream.next(m.fault_count);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WallPerchStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_wall_ceiling_control::WallPerchStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "state_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state_name);
    s << indent << "enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enabled);
    s << indent << "acquire_request: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.acquire_request);
    s << indent << "keep_ownership: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.keep_ownership);
    s << indent << "candidate_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.candidate_valid);
    s << indent << "front_range_fresh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.front_range_fresh);
    s << indent << "top_range_fresh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.top_range_fresh);
    s << indent << "sensor_health_fresh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensor_health_fresh);
    s << indent << "top_preflight_ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.top_preflight_ready);
    s << indent << "odom_fresh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.odom_fresh);
    s << indent << "flight_state_fresh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flight_state_fresh);
    s << indent << "front_ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.front_ready);
    s << indent << "flip_ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flip_ready);
    s << indent << "top_contact_ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.top_contact_ready);
    s << indent << "top_clear_ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.top_clear_ready);
    s << indent << "fault_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fault_detected);
    s << indent << "neutral_setpoint_requested: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.neutral_setpoint_requested);
    s << indent << "attitude_setpoint_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.attitude_setpoint_valid);
    s << indent << "front_distance_raw_m: ";
    Printer<float>::stream(s, indent + "  ", v.front_distance_raw_m);
    s << indent << "front_distance_filtered_m: ";
    Printer<float>::stream(s, indent + "  ", v.front_distance_filtered_m);
    s << indent << "top_distance_raw_m: ";
    Printer<float>::stream(s, indent + "  ", v.top_distance_raw_m);
    s << indent << "top_distance_filtered_m: ";
    Printer<float>::stream(s, indent + "  ", v.top_distance_filtered_m);
    s << indent << "progress: ";
    Printer<float>::stream(s, indent + "  ", v.progress);
    s << indent << "attitude_setpoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.attitude_setpoint);
    s << indent << "thrust_normalized: ";
    Printer<float>::stream(s, indent + "  ", v.thrust_normalized);
    s << indent << "fault_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.fault_count);
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_WALL_CEILING_CONTROL_MESSAGE_WALLPERCHSTATUS_H
