(cl:defpackage px4_wall_ceiling_control-msg
  (:use )
  (:export
   "<ATTACHMENTCONTROLCANDIDATE>"
   "ATTACHMENTCONTROLCANDIDATE"
   "<ATTACHMENTMECHANISMCOMMAND>"
   "ATTACHMENTMECHANISMCOMMAND"
   "<ATTACHMENTMECHANISMSTATUS>"
   "ATTACHMENTMECHANISMSTATUS"
   "<BEHAVIORCOMMAND>"
   "BEHAVIORCOMMAND"
   "<CEILINGATTACHMENTSTATUS>"
   "CEILINGATTACHMENTSTATUS"
   "<CONTROLSETPOINT>"
   "CONTROLSETPOINT"
   "<CONTROLLERSTATUS>"
   "CONTROLLERSTATUS"
   "<OPERATORCOMMAND>"
   "OPERATORCOMMAND"
   "<SENSORHEALTH>"
   "SENSORHEALTH"
   "<SUPERVISORSTATE>"
   "SUPERVISORSTATE"
   "<WALLPERCHSTATUS>"
   "WALLPERCHSTATUS"
  ))

