(cl:in-package px4_wall_ceiling_control-msg)
(cl:export '(HEADER-VAL
          HEADER
          STATE-VAL
          STATE
          ACTIVE_MODE-VAL
          ACTIVE_MODE
          SETPOINT_STREAM_ALLOWED-VAL
          SETPOINT_STREAM_ALLOWED
          MOTION_ALLOWED-VAL
          MOTION_ALLOWED
          MAVROS_CONNECTED-VAL
          MAVROS_CONNECTED
          ARMED-VAL
          ARMED
          OFFBOARD-VAL
          OFFBOARD
          OPERATOR_FRESH-VAL
          OPERATOR_FRESH
          ODOM_FRESH-VAL
          ODOM_FRESH
          CEILING_RANGE_FRESH-VAL
          CEILING_RANGE_FRESH
          WALL_RANGE_FRESH-VAL
          WALL_RANGE_FRESH
          FAULT_MASK-VAL
          FAULT_MASK
          REASON-VAL
          REASON
))