# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_wall_ceiling_control/AttachmentControlCandidate.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class AttachmentControlCandidate(genpy.Message):
  _md5sum = "a60e02517b779e0ed9645ce45b1715de"
  _type = "px4_wall_ceiling_control/AttachmentControlCandidate"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

uint8 SOURCE_NONE=0
uint8 SOURCE_CEILING=1
uint8 SOURCE_WALL=2

uint8 KIND_NONE=0
uint8 KIND_VERTICAL_VELOCITY=1
uint8 KIND_ATTITUDE_THRUST=2

uint8 source
uint8 kind
bool acquire_request
bool keep_ownership
bool valid

# ROS-side ENU world convention.
float32 velocity_z_enu_mps
# ROS-side ENU/FLU attitude convention; MAVROS performs PX4 conversion.
geometry_msgs/Quaternion attitude_setpoint
# Positive normalized collective thrust expected by mavros_msgs/AttitudeTarget.
float32 thrust_normalized
string reason


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  # Pseudo-constants
  SOURCE_NONE = 0
  SOURCE_CEILING = 1
  SOURCE_WALL = 2
  KIND_NONE = 0
  KIND_VERTICAL_VELOCITY = 1
  KIND_ATTITUDE_THRUST = 2

  __slots__ = ['header','source','kind','acquire_request','keep_ownership','valid','velocity_z_enu_mps','attitude_setpoint','thrust_normalized','reason']
  _slot_types = ['std_msgs/Header','uint8','uint8','bool','bool','bool','float32','geometry_msgs/Quaternion','float32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,source,kind,acquire_request,keep_ownership,valid,velocity_z_enu_mps,attitude_setpoint,thrust_normalized,reason

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AttachmentControlCandidate, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.source is None:
        self.source = 0
      if self.kind is None:
        self.kind = 0
      if self.acquire_request is None:
        self.acquire_request = False
      if self.keep_ownership is None:
        self.keep_ownership = False
      if self.valid is None:
        self.valid = False
      if self.velocity_z_enu_mps is None:
        self.velocity_z_enu_mps = 0.
      if self.attitude_setpoint is None:
        self.attitude_setpoint = geometry_msgs.msg.Quaternion()
      if self.thrust_normalized is None:
        self.thrust_normalized = 0.
      if self.reason is None:
        self.reason = ''
    else:
      self.header = std_msgs.msg.Header()
      self.source = 0
      self.kind = 0
      self.acquire_request = False
      self.keep_ownership = False
      self.valid = False
      self.velocity_z_enu_mps = 0.
      self.attitude_setpoint = geometry_msgs.msg.Quaternion()
      self.thrust_normalized = 0.
      self.reason = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_5Bf4df().pack(_x.source, _x.kind, _x.acquire_request, _x.keep_ownership, _x.valid, _x.velocity_z_enu_mps, _x.attitude_setpoint.x, _x.attitude_setpoint.y, _x.attitude_setpoint.z, _x.attitude_setpoint.w, _x.thrust_normalized))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.attitude_setpoint is None:
        self.attitude_setpoint = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 45
      (_x.source, _x.kind, _x.acquire_request, _x.keep_ownership, _x.valid, _x.velocity_z_enu_mps, _x.attitude_setpoint.x, _x.attitude_setpoint.y, _x.attitude_setpoint.z, _x.attitude_setpoint.w, _x.thrust_normalized,) = _get_struct_5Bf4df().unpack(str[start:end])
      self.acquire_request = bool(self.acquire_request)
      self.keep_ownership = bool(self.keep_ownership)
      self.valid = bool(self.valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_5Bf4df().pack(_x.source, _x.kind, _x.acquire_request, _x.keep_ownership, _x.valid, _x.velocity_z_enu_mps, _x.attitude_setpoint.x, _x.attitude_setpoint.y, _x.attitude_setpoint.z, _x.attitude_setpoint.w, _x.thrust_normalized))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.attitude_setpoint is None:
        self.attitude_setpoint = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 45
      (_x.source, _x.kind, _x.acquire_request, _x.keep_ownership, _x.valid, _x.velocity_z_enu_mps, _x.attitude_setpoint.x, _x.attitude_setpoint.y, _x.attitude_setpoint.z, _x.attitude_setpoint.w, _x.thrust_normalized,) = _get_struct_5Bf4df().unpack(str[start:end])
      self.acquire_request = bool(self.acquire_request)
      self.keep_ownership = bool(self.keep_ownership)
      self.valid = bool(self.valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_5Bf4df = None
def _get_struct_5Bf4df():
    global _struct_5Bf4df
    if _struct_5Bf4df is None:
        _struct_5Bf4df = struct.Struct("<5Bf4df")
    return _struct_5Bf4df
