# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_wall_ceiling_control/ControlSetpoint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import mavros_msgs.msg
import std_msgs.msg

class ControlSetpoint(genpy.Message):
  _md5sum = "905a0ba96daedb050b5d2c986dd2f262"
  _type = "px4_wall_ceiling_control/ControlSetpoint"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

uint8 SOURCE_NONE=0
uint8 SOURCE_CEILING=1
uint8 SOURCE_WALL=2

uint8 KIND_NONE=0
uint8 KIND_LOCAL=1
uint8 KIND_ATTITUDE=2

uint8 source
uint8 kind
bool valid
mavros_msgs/PositionTarget local
mavros_msgs/AttitudeTarget attitude
string reason

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: mavros_msgs/PositionTarget
# Message for SET_POSITION_TARGET_LOCAL_NED
#
# Some complex system requires all feautures that mavlink
# message provide. See issue #402.

std_msgs/Header header

uint8 coordinate_frame
uint8 FRAME_LOCAL_NED = 1
uint8 FRAME_LOCAL_OFFSET_NED = 7
uint8 FRAME_BODY_NED = 8
uint8 FRAME_BODY_OFFSET_NED = 9

uint16 type_mask
uint16 IGNORE_PX = 1	# Position ignore flags
uint16 IGNORE_PY = 2
uint16 IGNORE_PZ = 4
uint16 IGNORE_VX = 8	# Velocity vector ignore flags
uint16 IGNORE_VY = 16
uint16 IGNORE_VZ = 32
uint16 IGNORE_AFX = 64	# Acceleration/Force vector ignore flags
uint16 IGNORE_AFY = 128
uint16 IGNORE_AFZ = 256
uint16 FORCE = 512	# Force in af vector flag
uint16 IGNORE_YAW = 1024
uint16 IGNORE_YAW_RATE = 2048

geometry_msgs/Point position
geometry_msgs/Vector3 velocity
geometry_msgs/Vector3 acceleration_or_force
float32 yaw
float32 yaw_rate

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: mavros_msgs/AttitudeTarget
# Message for SET_ATTITUDE_TARGET
#
# Some complex system requires all feautures that mavlink
# message provide. See issue #402, #418.

std_msgs/Header header

uint8 type_mask
uint8 IGNORE_ROLL_RATE = 1	# body_rate.x
uint8 IGNORE_PITCH_RATE = 2	# body_rate.y
uint8 IGNORE_YAW_RATE = 4	# body_rate.z
uint8 IGNORE_THRUST = 64
uint8 IGNORE_ATTITUDE = 128	# orientation field

geometry_msgs/Quaternion orientation
geometry_msgs/Vector3 body_rate
float32 thrust

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  # Pseudo-constants
  SOURCE_NONE = 0
  SOURCE_CEILING = 1
  SOURCE_WALL = 2
  KIND_NONE = 0
  KIND_LOCAL = 1
  KIND_ATTITUDE = 2

  __slots__ = ['header','source','kind','valid','local','attitude','reason']
  _slot_types = ['std_msgs/Header','uint8','uint8','bool','mavros_msgs/PositionTarget','mavros_msgs/AttitudeTarget','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,source,kind,valid,local,attitude,reason

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ControlSetpoint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.source is None:
        self.source = 0
      if self.kind is None:
        self.kind = 0
      if self.valid is None:
        self.valid = False
      if self.local is None:
        self.local = mavros_msgs.msg.PositionTarget()
      if self.attitude is None:
        self.attitude = mavros_msgs.msg.AttitudeTarget()
      if self.reason is None:
        self.reason = ''
    else:
      self.header = std_msgs.msg.Header()
      self.source = 0
      self.kind = 0
      self.valid = False
      self.local = mavros_msgs.msg.PositionTarget()
      self.attitude = mavros_msgs.msg.AttitudeTarget()
      self.reason = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3B3I().pack(_x.source, _x.kind, _x.valid, _x.local.header.seq, _x.local.header.stamp.secs, _x.local.header.stamp.nsecs))
      _x = self.local.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BH9d2f3I().pack(_x.local.coordinate_frame, _x.local.type_mask, _x.local.position.x, _x.local.position.y, _x.local.position.z, _x.local.velocity.x, _x.local.velocity.y, _x.local.velocity.z, _x.local.acceleration_or_force.x, _x.local.acceleration_or_force.y, _x.local.acceleration_or_force.z, _x.local.yaw, _x.local.yaw_rate, _x.attitude.header.seq, _x.attitude.header.stamp.secs, _x.attitude.header.stamp.nsecs))
      _x = self.attitude.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B7df().pack(_x.attitude.type_mask, _x.attitude.orientation.x, _x.attitude.orientation.y, _x.attitude.orientation.z, _x.attitude.orientation.w, _x.attitude.body_rate.x, _x.attitude.body_rate.y, _x.attitude.body_rate.z, _x.attitude.thrust))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.local is None:
        self.local = mavros_msgs.msg.PositionTarget()
      if self.attitude is None:
        self.attitude = mavros_msgs.msg.AttitudeTarget()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.source, _x.kind, _x.valid, _x.local.header.seq, _x.local.header.stamp.secs, _x.local.header.stamp.nsecs,) = _get_struct_3B3I().unpack(str[start:end])
      self.valid = bool(self.valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.local.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.local.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 95
      (_x.local.coordinate_frame, _x.local.type_mask, _x.local.position.x, _x.local.position.y, _x.local.position.z, _x.local.velocity.x, _x.local.velocity.y, _x.local.velocity.z, _x.local.acceleration_or_force.x, _x.local.acceleration_or_force.y, _x.local.acceleration_or_force.z, _x.local.yaw, _x.local.yaw_rate, _x.attitude.header.seq, _x.attitude.header.stamp.secs, _x.attitude.header.stamp.nsecs,) = _get_struct_BH9d2f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attitude.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attitude.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 61
      (_x.attitude.type_mask, _x.attitude.orientation.x, _x.attitude.orientation.y, _x.attitude.orientation.z, _x.attitude.orientation.w, _x.attitude.body_rate.x, _x.attitude.body_rate.y, _x.attitude.body_rate.z, _x.attitude.thrust,) = _get_struct_B7df().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3B3I().pack(_x.source, _x.kind, _x.valid, _x.local.header.seq, _x.local.header.stamp.secs, _x.local.header.stamp.nsecs))
      _x = self.local.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BH9d2f3I().pack(_x.local.coordinate_frame, _x.local.type_mask, _x.local.position.x, _x.local.position.y, _x.local.position.z, _x.local.velocity.x, _x.local.velocity.y, _x.local.velocity.z, _x.local.acceleration_or_force.x, _x.local.acceleration_or_force.y, _x.local.acceleration_or_force.z, _x.local.yaw, _x.local.yaw_rate, _x.attitude.header.seq, _x.attitude.header.stamp.secs, _x.attitude.header.stamp.nsecs))
      _x = self.attitude.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B7df().pack(_x.attitude.type_mask, _x.attitude.orientation.x, _x.attitude.orientation.y, _x.attitude.orientation.z, _x.attitude.orientation.w, _x.attitude.body_rate.x, _x.attitude.body_rate.y, _x.attitude.body_rate.z, _x.attitude.thrust))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.local is None:
        self.local = mavros_msgs.msg.PositionTarget()
      if self.attitude is None:
        self.attitude = mavros_msgs.msg.AttitudeTarget()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.source, _x.kind, _x.valid, _x.local.header.seq, _x.local.header.stamp.secs, _x.local.header.stamp.nsecs,) = _get_struct_3B3I().unpack(str[start:end])
      self.valid = bool(self.valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.local.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.local.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 95
      (_x.local.coordinate_frame, _x.local.type_mask, _x.local.position.x, _x.local.position.y, _x.local.position.z, _x.local.velocity.x, _x.local.velocity.y, _x.local.velocity.z, _x.local.acceleration_or_force.x, _x.local.acceleration_or_force.y, _x.local.acceleration_or_force.z, _x.local.yaw, _x.local.yaw_rate, _x.attitude.header.seq, _x.attitude.header.stamp.secs, _x.attitude.header.stamp.nsecs,) = _get_struct_BH9d2f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attitude.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attitude.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 61
      (_x.attitude.type_mask, _x.attitude.orientation.x, _x.attitude.orientation.y, _x.attitude.orientation.z, _x.attitude.orientation.w, _x.attitude.body_rate.x, _x.attitude.body_rate.y, _x.attitude.body_rate.z, _x.attitude.thrust,) = _get_struct_B7df().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B3I = None
def _get_struct_3B3I():
    global _struct_3B3I
    if _struct_3B3I is None:
        _struct_3B3I = struct.Struct("<3B3I")
    return _struct_3B3I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B7df = None
def _get_struct_B7df():
    global _struct_B7df
    if _struct_B7df is None:
        _struct_B7df = struct.Struct("<B7df")
    return _struct_B7df
_struct_BH9d2f3I = None
def _get_struct_BH9d2f3I():
    global _struct_BH9d2f3I
    if _struct_BH9d2f3I is None:
        _struct_BH9d2f3I = struct.Struct("<BH9d2f3I")
    return _struct_BH9d2f3I
