# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_wall_ceiling_control/SensorHealth.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class SensorHealth(genpy.Message):
  _md5sum = "890f31b2daff364b0bc989c3503517bf"
  _type = "px4_wall_ceiling_control/SensorHealth"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

bool ceiling_valid
bool front_valid

# Age of the last valid sample as measured at this node. Infinity means that
# no valid sample has been received since startup.
float32 ceiling_age_s
float32 front_age_s

# Monotonic counters allow consumers and tests to distinguish real samples
# from repeated status publications.
uint32 ceiling_sequence
uint32 front_sequence
uint32 ceiling_invalid_count
uint32 front_invalid_count

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','ceiling_valid','front_valid','ceiling_age_s','front_age_s','ceiling_sequence','front_sequence','ceiling_invalid_count','front_invalid_count']
  _slot_types = ['std_msgs/Header','bool','bool','float32','float32','uint32','uint32','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ceiling_valid,front_valid,ceiling_age_s,front_age_s,ceiling_sequence,front_sequence,ceiling_invalid_count,front_invalid_count

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SensorHealth, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ceiling_valid is None:
        self.ceiling_valid = False
      if self.front_valid is None:
        self.front_valid = False
      if self.ceiling_age_s is None:
        self.ceiling_age_s = 0.
      if self.front_age_s is None:
        self.front_age_s = 0.
      if self.ceiling_sequence is None:
        self.ceiling_sequence = 0
      if self.front_sequence is None:
        self.front_sequence = 0
      if self.ceiling_invalid_count is None:
        self.ceiling_invalid_count = 0
      if self.front_invalid_count is None:
        self.front_invalid_count = 0
    else:
      self.header = std_msgs.msg.Header()
      self.ceiling_valid = False
      self.front_valid = False
      self.ceiling_age_s = 0.
      self.front_age_s = 0.
      self.ceiling_sequence = 0
      self.front_sequence = 0
      self.ceiling_invalid_count = 0
      self.front_invalid_count = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B2f4I().pack(_x.ceiling_valid, _x.front_valid, _x.ceiling_age_s, _x.front_age_s, _x.ceiling_sequence, _x.front_sequence, _x.ceiling_invalid_count, _x.front_invalid_count))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 26
      (_x.ceiling_valid, _x.front_valid, _x.ceiling_age_s, _x.front_age_s, _x.ceiling_sequence, _x.front_sequence, _x.ceiling_invalid_count, _x.front_invalid_count,) = _get_struct_2B2f4I().unpack(str[start:end])
      self.ceiling_valid = bool(self.ceiling_valid)
      self.front_valid = bool(self.front_valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B2f4I().pack(_x.ceiling_valid, _x.front_valid, _x.ceiling_age_s, _x.front_age_s, _x.ceiling_sequence, _x.front_sequence, _x.ceiling_invalid_count, _x.front_invalid_count))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 26
      (_x.ceiling_valid, _x.front_valid, _x.ceiling_age_s, _x.front_age_s, _x.ceiling_sequence, _x.front_sequence, _x.ceiling_invalid_count, _x.front_invalid_count,) = _get_struct_2B2f4I().unpack(str[start:end])
      self.ceiling_valid = bool(self.ceiling_valid)
      self.front_valid = bool(self.front_valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B2f4I = None
def _get_struct_2B2f4I():
    global _struct_2B2f4I
    if _struct_2B2f4I is None:
        _struct_2B2f4I = struct.Struct("<2B2f4I")
    return _struct_2B2f4I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
