# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_wall_ceiling_control/SupervisorState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class SupervisorState(genpy.Message):
  _md5sum = "1ec3406c7c8a31f63daae31442cabb75"
  _type = "px4_wall_ceiling_control/SupervisorState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

uint8 STATE_WAIT_LINK=0
uint8 STATE_MANUAL=1
uint8 STATE_STANDBY=2
uint8 STATE_PRESTREAM=3
uint8 STATE_CEILING_ACTIVE=4
uint8 STATE_WALL_ACTIVE=5
uint8 STATE_FAULT=6

uint8 MODE_NONE=0
uint8 MODE_CEILING=1
uint8 MODE_WALL=2

uint32 FAULT_NONE=0
uint32 FAULT_MAVROS=1
uint32 FAULT_OPERATOR=2
uint32 FAULT_ODOMETRY=4
uint32 FAULT_CEILING_RANGE=8
uint32 FAULT_WALL_RANGE=16
uint32 FAULT_UNKNOWN_MODE=32

uint8 state
uint8 active_mode
bool setpoint_stream_allowed
bool motion_allowed
bool mavros_connected
bool armed
bool offboard
bool operator_fresh
bool odom_fresh
bool ceiling_range_fresh
bool wall_range_fresh
uint32 fault_mask
string reason

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  # Pseudo-constants
  STATE_WAIT_LINK = 0
  STATE_MANUAL = 1
  STATE_STANDBY = 2
  STATE_PRESTREAM = 3
  STATE_CEILING_ACTIVE = 4
  STATE_WALL_ACTIVE = 5
  STATE_FAULT = 6
  MODE_NONE = 0
  MODE_CEILING = 1
  MODE_WALL = 2
  FAULT_NONE = 0
  FAULT_MAVROS = 1
  FAULT_OPERATOR = 2
  FAULT_ODOMETRY = 4
  FAULT_CEILING_RANGE = 8
  FAULT_WALL_RANGE = 16
  FAULT_UNKNOWN_MODE = 32

  __slots__ = ['header','state','active_mode','setpoint_stream_allowed','motion_allowed','mavros_connected','armed','offboard','operator_fresh','odom_fresh','ceiling_range_fresh','wall_range_fresh','fault_mask','reason']
  _slot_types = ['std_msgs/Header','uint8','uint8','bool','bool','bool','bool','bool','bool','bool','bool','bool','uint32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,state,active_mode,setpoint_stream_allowed,motion_allowed,mavros_connected,armed,offboard,operator_fresh,odom_fresh,ceiling_range_fresh,wall_range_fresh,fault_mask,reason

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SupervisorState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.state is None:
        self.state = 0
      if self.active_mode is None:
        self.active_mode = 0
      if self.setpoint_stream_allowed is None:
        self.setpoint_stream_allowed = False
      if self.motion_allowed is None:
        self.motion_allowed = False
      if self.mavros_connected is None:
        self.mavros_connected = False
      if self.armed is None:
        self.armed = False
      if self.offboard is None:
        self.offboard = False
      if self.operator_fresh is None:
        self.operator_fresh = False
      if self.odom_fresh is None:
        self.odom_fresh = False
      if self.ceiling_range_fresh is None:
        self.ceiling_range_fresh = False
      if self.wall_range_fresh is None:
        self.wall_range_fresh = False
      if self.fault_mask is None:
        self.fault_mask = 0
      if self.reason is None:
        self.reason = ''
    else:
      self.header = std_msgs.msg.Header()
      self.state = 0
      self.active_mode = 0
      self.setpoint_stream_allowed = False
      self.motion_allowed = False
      self.mavros_connected = False
      self.armed = False
      self.offboard = False
      self.operator_fresh = False
      self.odom_fresh = False
      self.ceiling_range_fresh = False
      self.wall_range_fresh = False
      self.fault_mask = 0
      self.reason = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_11BI().pack(_x.state, _x.active_mode, _x.setpoint_stream_allowed, _x.motion_allowed, _x.mavros_connected, _x.armed, _x.offboard, _x.operator_fresh, _x.odom_fresh, _x.ceiling_range_fresh, _x.wall_range_fresh, _x.fault_mask))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.state, _x.active_mode, _x.setpoint_stream_allowed, _x.motion_allowed, _x.mavros_connected, _x.armed, _x.offboard, _x.operator_fresh, _x.odom_fresh, _x.ceiling_range_fresh, _x.wall_range_fresh, _x.fault_mask,) = _get_struct_11BI().unpack(str[start:end])
      self.setpoint_stream_allowed = bool(self.setpoint_stream_allowed)
      self.motion_allowed = bool(self.motion_allowed)
      self.mavros_connected = bool(self.mavros_connected)
      self.armed = bool(self.armed)
      self.offboard = bool(self.offboard)
      self.operator_fresh = bool(self.operator_fresh)
      self.odom_fresh = bool(self.odom_fresh)
      self.ceiling_range_fresh = bool(self.ceiling_range_fresh)
      self.wall_range_fresh = bool(self.wall_range_fresh)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_11BI().pack(_x.state, _x.active_mode, _x.setpoint_stream_allowed, _x.motion_allowed, _x.mavros_connected, _x.armed, _x.offboard, _x.operator_fresh, _x.odom_fresh, _x.ceiling_range_fresh, _x.wall_range_fresh, _x.fault_mask))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.state, _x.active_mode, _x.setpoint_stream_allowed, _x.motion_allowed, _x.mavros_connected, _x.armed, _x.offboard, _x.operator_fresh, _x.odom_fresh, _x.ceiling_range_fresh, _x.wall_range_fresh, _x.fault_mask,) = _get_struct_11BI().unpack(str[start:end])
      self.setpoint_stream_allowed = bool(self.setpoint_stream_allowed)
      self.motion_allowed = bool(self.motion_allowed)
      self.mavros_connected = bool(self.mavros_connected)
      self.armed = bool(self.armed)
      self.offboard = bool(self.offboard)
      self.operator_fresh = bool(self.operator_fresh)
      self.odom_fresh = bool(self.odom_fresh)
      self.ceiling_range_fresh = bool(self.ceiling_range_fresh)
      self.wall_range_fresh = bool(self.wall_range_fresh)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_11BI = None
def _get_struct_11BI():
    global _struct_11BI
    if _struct_11BI is None:
        _struct_11BI = struct.Struct("<11BI")
    return _struct_11BI
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
