// Generated by gencpp from file px4_wall_ceiling_control/AttachmentMechanismStatus.msg
// DO NOT EDIT!


#ifndef PX4_WALL_CEILING_CONTROL_MESSAGE_ATTACHMENTMECHANISMSTATUS_H
#define PX4_WALL_CEILING_CONTROL_MESSAGE_ATTACHMENTMECHANISMSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace px4_wall_ceiling_control
{
template <class ContainerAllocator>
struct AttachmentMechanismStatus_
{
  typedef AttachmentMechanismStatus_<ContainerAllocator> Type;

  AttachmentMechanismStatus_()
    : header()
    , source(0)
    , sequence(0)
    , acknowledged(false)
    , released(false)
    , fault(false)
    , reason()  {
    }
  AttachmentMechanismStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , source(0)
    , sequence(0)
    , acknowledged(false)
    , released(false)
    , fault(false)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _source_type;
  _source_type source;

   typedef uint32_t _sequence_type;
  _sequence_type sequence;

   typedef uint8_t _acknowledged_type;
  _acknowledged_type acknowledged;

   typedef uint8_t _released_type;
  _released_type released;

   typedef uint8_t _fault_type;
  _fault_type fault;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;





  typedef boost::shared_ptr< ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator> const> ConstPtr;

}; // struct AttachmentMechanismStatus_

typedef ::px4_wall_ceiling_control::AttachmentMechanismStatus_<std::allocator<void> > AttachmentMechanismStatus;

typedef boost::shared_ptr< ::px4_wall_ceiling_control::AttachmentMechanismStatus > AttachmentMechanismStatusPtr;
typedef boost::shared_ptr< ::px4_wall_ceiling_control::AttachmentMechanismStatus const> AttachmentMechanismStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.source == rhs.source &&
    lhs.sequence == rhs.sequence &&
    lhs.acknowledged == rhs.acknowledged &&
    lhs.released == rhs.released &&
    lhs.fault == rhs.fault &&
    lhs.reason == rhs.reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_wall_ceiling_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3810df96eca58328a3f90eb36d48cc3";
  }

  static const char* value(const ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3810df96eca5832ULL;
  static const uint64_t static_value2 = 0x8a3f90eb36d48cc3ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_wall_ceiling_control/AttachmentMechanismStatus";
  }

  static const char* value(const ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 source\n"
"uint32 sequence\n"
"bool acknowledged\n"
"bool released\n"
"bool fault\n"
"string reason\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.source);
      stream.next(m.sequence);
      stream.next(m.acknowledged);
      stream.next(m.released);
      stream.next(m.fault);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AttachmentMechanismStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_wall_ceiling_control::AttachmentMechanismStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "source: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.source);
    s << indent << "sequence: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.sequence);
    s << indent << "acknowledged: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.acknowledged);
    s << indent << "released: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.released);
    s << indent << "fault: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fault);
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_WALL_CEILING_CONTROL_MESSAGE_ATTACHMENTMECHANISMSTATUS_H
