// Generated by gencpp from file px4_wall_ceiling_control/CeilingAttachmentStatus.msg
// DO NOT EDIT!


#ifndef PX4_WALL_CEILING_CONTROL_MESSAGE_CEILINGATTACHMENTSTATUS_H
#define PX4_WALL_CEILING_CONTROL_MESSAGE_CEILINGATTACHMENTSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>

namespace px4_wall_ceiling_control
{
template <class ContainerAllocator>
struct CeilingAttachmentStatus_
{
  typedef CeilingAttachmentStatus_<ContainerAllocator> Type;

  CeilingAttachmentStatus_()
    : header()
    , state(0)
    , state_name()
    , enabled(false)
    , acquire_request(false)
    , keep_ownership(false)
    , candidate_valid(false)
    , range_fresh(false)
    , odom_fresh(false)
    , flight_state_fresh(false)
    , attach_confirmed(false)
    , distance_stable(false)
    , fault_detected(false)
    , detach_failed(false)
    , integral_reset_request(false)
    , wheel_stop_request(false)
    , mechanism_release_requested(false)
    , mechanism_release_confirmed(false)
    , ceiling_distance_raw_m(0.0)
    , ceiling_distance_filtered_m(0.0)
    , target_distance_m(0.0)
    , compression_m(0.0)
    , target_compression_m(0.0)
    , approach_velocity_z_enu_mps(0.0)
    , thrust_body_z_normalized(0.0)
    , attitude_setpoint_valid(false)
    , attitude_setpoint()
    , fault_count(0)
    , reason()  {
    }
  CeilingAttachmentStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)
    , state_name(_alloc)
    , enabled(false)
    , acquire_request(false)
    , keep_ownership(false)
    , candidate_valid(false)
    , range_fresh(false)
    , odom_fresh(false)
    , flight_state_fresh(false)
    , attach_confirmed(false)
    , distance_stable(false)
    , fault_detected(false)
    , detach_failed(false)
    , integral_reset_request(false)
    , wheel_stop_request(false)
    , mechanism_release_requested(false)
    , mechanism_release_confirmed(false)
    , ceiling_distance_raw_m(0.0)
    , ceiling_distance_filtered_m(0.0)
    , target_distance_m(0.0)
    , compression_m(0.0)
    , target_compression_m(0.0)
    , approach_velocity_z_enu_mps(0.0)
    , thrust_body_z_normalized(0.0)
    , attitude_setpoint_valid(false)
    , attitude_setpoint(_alloc)
    , fault_count(0)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_name_type;
  _state_name_type state_name;

   typedef uint8_t _enabled_type;
  _enabled_type enabled;

   typedef uint8_t _acquire_request_type;
  _acquire_request_type acquire_request;

   typedef uint8_t _keep_ownership_type;
  _keep_ownership_type keep_ownership;

   typedef uint8_t _candidate_valid_type;
  _candidate_valid_type candidate_valid;

   typedef uint8_t _range_fresh_type;
  _range_fresh_type range_fresh;

   typedef uint8_t _odom_fresh_type;
  _odom_fresh_type odom_fresh;

   typedef uint8_t _flight_state_fresh_type;
  _flight_state_fresh_type flight_state_fresh;

   typedef uint8_t _attach_confirmed_type;
  _attach_confirmed_type attach_confirmed;

   typedef uint8_t _distance_stable_type;
  _distance_stable_type distance_stable;

   typedef uint8_t _fault_detected_type;
  _fault_detected_type fault_detected;

   typedef uint8_t _detach_failed_type;
  _detach_failed_type detach_failed;

   typedef uint8_t _integral_reset_request_type;
  _integral_reset_request_type integral_reset_request;

   typedef uint8_t _wheel_stop_request_type;
  _wheel_stop_request_type wheel_stop_request;

   typedef uint8_t _mechanism_release_requested_type;
  _mechanism_release_requested_type mechanism_release_requested;

   typedef uint8_t _mechanism_release_confirmed_type;
  _mechanism_release_confirmed_type mechanism_release_confirmed;

   typedef float _ceiling_distance_raw_m_type;
  _ceiling_distance_raw_m_type ceiling_distance_raw_m;

   typedef float _ceiling_distance_filtered_m_type;
  _ceiling_distance_filtered_m_type ceiling_distance_filtered_m;

   typedef float _target_distance_m_type;
  _target_distance_m_type target_distance_m;

   typedef float _compression_m_type;
  _compression_m_type compression_m;

   typedef float _target_compression_m_type;
  _target_compression_m_type target_compression_m;

   typedef float _approach_velocity_z_enu_mps_type;
  _approach_velocity_z_enu_mps_type approach_velocity_z_enu_mps;

   typedef float _thrust_body_z_normalized_type;
  _thrust_body_z_normalized_type thrust_body_z_normalized;

   typedef uint8_t _attitude_setpoint_valid_type;
  _attitude_setpoint_valid_type attitude_setpoint_valid;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _attitude_setpoint_type;
  _attitude_setpoint_type attitude_setpoint;

   typedef uint32_t _fault_count_type;
  _fault_count_type fault_count;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STATE_NORMAL_FLIGHT)
  #undef STATE_NORMAL_FLIGHT
#endif
#if defined(_WIN32) && defined(STATE_CEILING_ARMED)
  #undef STATE_CEILING_ARMED
#endif
#if defined(_WIN32) && defined(STATE_APPROACH)
  #undef STATE_APPROACH
#endif
#if defined(_WIN32) && defined(STATE_ATTACH_CONTROL)
  #undef STATE_ATTACH_CONTROL
#endif
#if defined(_WIN32) && defined(STATE_SURFACE_HOLD)
  #undef STATE_SURFACE_HOLD
#endif
#if defined(_WIN32) && defined(STATE_DETACH)
  #undef STATE_DETACH
#endif
#if defined(_WIN32) && defined(STATE_RECOVERY_HOVER)
  #undef STATE_RECOVERY_HOVER
#endif
#if defined(_WIN32) && defined(STATE_FAULT)
  #undef STATE_FAULT
#endif

  enum {
    STATE_NORMAL_FLIGHT = 0u,
    STATE_CEILING_ARMED = 1u,
    STATE_APPROACH = 2u,
    STATE_ATTACH_CONTROL = 3u,
    STATE_SURFACE_HOLD = 4u,
    STATE_DETACH = 5u,
    STATE_RECOVERY_HOVER = 6u,
    STATE_FAULT = 7u,
  };


  typedef boost::shared_ptr< ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator> const> ConstPtr;

}; // struct CeilingAttachmentStatus_

typedef ::px4_wall_ceiling_control::CeilingAttachmentStatus_<std::allocator<void> > CeilingAttachmentStatus;

typedef boost::shared_ptr< ::px4_wall_ceiling_control::CeilingAttachmentStatus > CeilingAttachmentStatusPtr;
typedef boost::shared_ptr< ::px4_wall_ceiling_control::CeilingAttachmentStatus const> CeilingAttachmentStatusConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state &&
    lhs.state_name == rhs.state_name &&
    lhs.enabled == rhs.enabled &&
    lhs.acquire_request == rhs.acquire_request &&
    lhs.keep_ownership == rhs.keep_ownership &&
    lhs.candidate_valid == rhs.candidate_valid &&
    lhs.range_fresh == rhs.range_fresh &&
    lhs.odom_fresh == rhs.odom_fresh &&
    lhs.flight_state_fresh == rhs.flight_state_fresh &&
    lhs.attach_confirmed == rhs.attach_confirmed &&
    lhs.distance_stable == rhs.distance_stable &&
    lhs.fault_detected == rhs.fault_detected &&
    lhs.detach_failed == rhs.detach_failed &&
    lhs.integral_reset_request == rhs.integral_reset_request &&
    lhs.wheel_stop_request == rhs.wheel_stop_request &&
    lhs.mechanism_release_requested == rhs.mechanism_release_requested &&
    lhs.mechanism_release_confirmed == rhs.mechanism_release_confirmed &&
    lhs.ceiling_distance_raw_m == rhs.ceiling_distance_raw_m &&
    lhs.ceiling_distance_filtered_m == rhs.ceiling_distance_filtered_m &&
    lhs.target_distance_m == rhs.target_distance_m &&
    lhs.compression_m == rhs.compression_m &&
    lhs.target_compression_m == rhs.target_compression_m &&
    lhs.approach_velocity_z_enu_mps == rhs.approach_velocity_z_enu_mps &&
    lhs.thrust_body_z_normalized == rhs.thrust_body_z_normalized &&
    lhs.attitude_setpoint_valid == rhs.attitude_setpoint_valid &&
    lhs.attitude_setpoint == rhs.attitude_setpoint &&
    lhs.fault_count == rhs.fault_count &&
    lhs.reason == rhs.reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_wall_ceiling_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee6fc76925906c4e79bd0785bd2ec2d9";
  }

  static const char* value(const ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee6fc76925906c4eULL;
  static const uint64_t static_value2 = 0x79bd0785bd2ec2d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_wall_ceiling_control/CeilingAttachmentStatus";
  }

  static const char* value(const ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 STATE_NORMAL_FLIGHT=0\n"
"uint8 STATE_CEILING_ARMED=1\n"
"uint8 STATE_APPROACH=2\n"
"uint8 STATE_ATTACH_CONTROL=3\n"
"uint8 STATE_SURFACE_HOLD=4\n"
"uint8 STATE_DETACH=5\n"
"uint8 STATE_RECOVERY_HOVER=6\n"
"uint8 STATE_FAULT=7\n"
"\n"
"uint8 state\n"
"string state_name\n"
"bool enabled\n"
"bool acquire_request\n"
"bool keep_ownership\n"
"bool candidate_valid\n"
"bool range_fresh\n"
"bool odom_fresh\n"
"bool flight_state_fresh\n"
"bool attach_confirmed\n"
"bool distance_stable\n"
"bool fault_detected\n"
"bool detach_failed\n"
"bool integral_reset_request\n"
"bool wheel_stop_request\n"
"bool mechanism_release_requested\n"
"bool mechanism_release_confirmed\n"
"float32 ceiling_distance_raw_m\n"
"float32 ceiling_distance_filtered_m\n"
"float32 target_distance_m\n"
"float32 compression_m\n"
"float32 target_compression_m\n"
"# ROS/MAVROS ENU convention: positive z means upward/toward a horizontal ceiling.\n"
"float32 approach_velocity_z_enu_mps\n"
"# PX4 body FRD convention retained from the reference: negative z is upward thrust.\n"
"float32 thrust_body_z_normalized\n"
"bool attitude_setpoint_valid\n"
"geometry_msgs/Quaternion attitude_setpoint\n"
"uint32 fault_count\n"
"string reason\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.state_name);
      stream.next(m.enabled);
      stream.next(m.acquire_request);
      stream.next(m.keep_ownership);
      stream.next(m.candidate_valid);
      stream.next(m.range_fresh);
      stream.next(m.odom_fresh);
      stream.next(m.flight_state_fresh);
      stream.next(m.attach_confirmed);
      stream.next(m.distance_stable);
      stream.next(m.fault_detected);
      stream.next(m.detach_failed);
      stream.next(m.integral_reset_request);
      stream.next(m.wheel_stop_request);
      stream.next(m.mechanism_release_requested);
      stream.next(m.mechanism_release_confirmed);
      stream.next(m.ceiling_distance_raw_m);
      stream.next(m.ceiling_distance_filtered_m);
      stream.next(m.target_distance_m);
      stream.next(m.compression_m);
      stream.next(m.target_compression_m);
      stream.next(m.approach_velocity_z_enu_mps);
      stream.next(m.thrust_body_z_normalized);
      stream.next(m.attitude_setpoint_valid);
      stream.next(m.attitude_setpoint);
      stream.next(m.fault_count);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CeilingAttachmentStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_wall_ceiling_control::CeilingAttachmentStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "state_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state_name);
    s << indent << "enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enabled);
    s << indent << "acquire_request: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.acquire_request);
    s << indent << "keep_ownership: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.keep_ownership);
    s << indent << "candidate_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.candidate_valid);
    s << indent << "range_fresh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.range_fresh);
    s << indent << "odom_fresh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.odom_fresh);
    s << indent << "flight_state_fresh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flight_state_fresh);
    s << indent << "attach_confirmed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.attach_confirmed);
    s << indent << "distance_stable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.distance_stable);
    s << indent << "fault_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fault_detected);
    s << indent << "detach_failed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detach_failed);
    s << indent << "integral_reset_request: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.integral_reset_request);
    s << indent << "wheel_stop_request: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wheel_stop_request);
    s << indent << "mechanism_release_requested: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mechanism_release_requested);
    s << indent << "mechanism_release_confirmed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mechanism_release_confirmed);
    s << indent << "ceiling_distance_raw_m: ";
    Printer<float>::stream(s, indent + "  ", v.ceiling_distance_raw_m);
    s << indent << "ceiling_distance_filtered_m: ";
    Printer<float>::stream(s, indent + "  ", v.ceiling_distance_filtered_m);
    s << indent << "target_distance_m: ";
    Printer<float>::stream(s, indent + "  ", v.target_distance_m);
    s << indent << "compression_m: ";
    Printer<float>::stream(s, indent + "  ", v.compression_m);
    s << indent << "target_compression_m: ";
    Printer<float>::stream(s, indent + "  ", v.target_compression_m);
    s << indent << "approach_velocity_z_enu_mps: ";
    Printer<float>::stream(s, indent + "  ", v.approach_velocity_z_enu_mps);
    s << indent << "thrust_body_z_normalized: ";
    Printer<float>::stream(s, indent + "  ", v.thrust_body_z_normalized);
    s << indent << "attitude_setpoint_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.attitude_setpoint_valid);
    s << indent << "attitude_setpoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.attitude_setpoint);
    s << indent << "fault_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.fault_count);
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_WALL_CEILING_CONTROL_MESSAGE_CEILINGATTACHMENTSTATUS_H
