// Generated by gencpp from file px4_wall_ceiling_control/ControllerStatus.msg
// DO NOT EDIT!


#ifndef PX4_WALL_CEILING_CONTROL_MESSAGE_CONTROLLERSTATUS_H
#define PX4_WALL_CEILING_CONTROL_MESSAGE_CONTROLLERSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace px4_wall_ceiling_control
{
template <class ContainerAllocator>
struct ControllerStatus_
{
  typedef ControllerStatus_<ContainerAllocator> Type;

  ControllerStatus_()
    : header()
    , source(0)
    , healthy(false)
    , input_fresh(false)
    , target_reached(false)
    , detail()  {
    }
  ControllerStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , source(0)
    , healthy(false)
    , input_fresh(false)
    , target_reached(false)
    , detail(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _source_type;
  _source_type source;

   typedef uint8_t _healthy_type;
  _healthy_type healthy;

   typedef uint8_t _input_fresh_type;
  _input_fresh_type input_fresh;

   typedef uint8_t _target_reached_type;
  _target_reached_type target_reached;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _detail_type;
  _detail_type detail;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SOURCE_NONE)
  #undef SOURCE_NONE
#endif
#if defined(_WIN32) && defined(SOURCE_CEILING)
  #undef SOURCE_CEILING
#endif
#if defined(_WIN32) && defined(SOURCE_WALL)
  #undef SOURCE_WALL
#endif

  enum {
    SOURCE_NONE = 0u,
    SOURCE_CEILING = 1u,
    SOURCE_WALL = 2u,
  };


  typedef boost::shared_ptr< ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerStatus_

typedef ::px4_wall_ceiling_control::ControllerStatus_<std::allocator<void> > ControllerStatus;

typedef boost::shared_ptr< ::px4_wall_ceiling_control::ControllerStatus > ControllerStatusPtr;
typedef boost::shared_ptr< ::px4_wall_ceiling_control::ControllerStatus const> ControllerStatusConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.source == rhs.source &&
    lhs.healthy == rhs.healthy &&
    lhs.input_fresh == rhs.input_fresh &&
    lhs.target_reached == rhs.target_reached &&
    lhs.detail == rhs.detail;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_wall_ceiling_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4190f296fb56a105a72ae34460a659f";
  }

  static const char* value(const ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4190f296fb56a10ULL;
  static const uint64_t static_value2 = 0x5a72ae34460a659fULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_wall_ceiling_control/ControllerStatus";
  }

  static const char* value(const ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 SOURCE_NONE=0\n"
"uint8 SOURCE_CEILING=1\n"
"uint8 SOURCE_WALL=2\n"
"\n"
"uint8 source\n"
"bool healthy\n"
"bool input_fresh\n"
"bool target_reached\n"
"string detail\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.source);
      stream.next(m.healthy);
      stream.next(m.input_fresh);
      stream.next(m.target_reached);
      stream.next(m.detail);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllerStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_wall_ceiling_control::ControllerStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "source: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.source);
    s << indent << "healthy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.healthy);
    s << indent << "input_fresh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.input_fresh);
    s << indent << "target_reached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_reached);
    s << indent << "detail: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.detail);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_WALL_CEILING_CONTROL_MESSAGE_CONTROLLERSTATUS_H
