// Generated by gencpp from file px4_wall_ceiling_control/ControlSetpoint.msg
// DO NOT EDIT!


#ifndef PX4_WALL_CEILING_CONTROL_MESSAGE_CONTROLSETPOINT_H
#define PX4_WALL_CEILING_CONTROL_MESSAGE_CONTROLSETPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mavros_msgs/PositionTarget.h>
#include <mavros_msgs/AttitudeTarget.h>

namespace px4_wall_ceiling_control
{
template <class ContainerAllocator>
struct ControlSetpoint_
{
  typedef ControlSetpoint_<ContainerAllocator> Type;

  ControlSetpoint_()
    : header()
    , source(0)
    , kind(0)
    , valid(false)
    , local()
    , attitude()
    , reason()  {
    }
  ControlSetpoint_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , source(0)
    , kind(0)
    , valid(false)
    , local(_alloc)
    , attitude(_alloc)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _source_type;
  _source_type source;

   typedef uint8_t _kind_type;
  _kind_type kind;

   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef  ::mavros_msgs::PositionTarget_<ContainerAllocator>  _local_type;
  _local_type local;

   typedef  ::mavros_msgs::AttitudeTarget_<ContainerAllocator>  _attitude_type;
  _attitude_type attitude;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SOURCE_NONE)
  #undef SOURCE_NONE
#endif
#if defined(_WIN32) && defined(SOURCE_CEILING)
  #undef SOURCE_CEILING
#endif
#if defined(_WIN32) && defined(SOURCE_WALL)
  #undef SOURCE_WALL
#endif
#if defined(_WIN32) && defined(KIND_NONE)
  #undef KIND_NONE
#endif
#if defined(_WIN32) && defined(KIND_LOCAL)
  #undef KIND_LOCAL
#endif
#if defined(_WIN32) && defined(KIND_ATTITUDE)
  #undef KIND_ATTITUDE
#endif

  enum {
    SOURCE_NONE = 0u,
    SOURCE_CEILING = 1u,
    SOURCE_WALL = 2u,
    KIND_NONE = 0u,
    KIND_LOCAL = 1u,
    KIND_ATTITUDE = 2u,
  };


  typedef boost::shared_ptr< ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator> const> ConstPtr;

}; // struct ControlSetpoint_

typedef ::px4_wall_ceiling_control::ControlSetpoint_<std::allocator<void> > ControlSetpoint;

typedef boost::shared_ptr< ::px4_wall_ceiling_control::ControlSetpoint > ControlSetpointPtr;
typedef boost::shared_ptr< ::px4_wall_ceiling_control::ControlSetpoint const> ControlSetpointConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.source == rhs.source &&
    lhs.kind == rhs.kind &&
    lhs.valid == rhs.valid &&
    lhs.local == rhs.local &&
    lhs.attitude == rhs.attitude &&
    lhs.reason == rhs.reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_wall_ceiling_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "905a0ba96daedb050b5d2c986dd2f262";
  }

  static const char* value(const ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x905a0ba96daedb05ULL;
  static const uint64_t static_value2 = 0x0b5d2c986dd2f262ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_wall_ceiling_control/ControlSetpoint";
  }

  static const char* value(const ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 SOURCE_NONE=0\n"
"uint8 SOURCE_CEILING=1\n"
"uint8 SOURCE_WALL=2\n"
"\n"
"uint8 KIND_NONE=0\n"
"uint8 KIND_LOCAL=1\n"
"uint8 KIND_ATTITUDE=2\n"
"\n"
"uint8 source\n"
"uint8 kind\n"
"bool valid\n"
"mavros_msgs/PositionTarget local\n"
"mavros_msgs/AttitudeTarget attitude\n"
"string reason\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: mavros_msgs/PositionTarget\n"
"# Message for SET_POSITION_TARGET_LOCAL_NED\n"
"#\n"
"# Some complex system requires all feautures that mavlink\n"
"# message provide. See issue #402.\n"
"\n"
"std_msgs/Header header\n"
"\n"
"uint8 coordinate_frame\n"
"uint8 FRAME_LOCAL_NED = 1\n"
"uint8 FRAME_LOCAL_OFFSET_NED = 7\n"
"uint8 FRAME_BODY_NED = 8\n"
"uint8 FRAME_BODY_OFFSET_NED = 9\n"
"\n"
"uint16 type_mask\n"
"uint16 IGNORE_PX = 1	# Position ignore flags\n"
"uint16 IGNORE_PY = 2\n"
"uint16 IGNORE_PZ = 4\n"
"uint16 IGNORE_VX = 8	# Velocity vector ignore flags\n"
"uint16 IGNORE_VY = 16\n"
"uint16 IGNORE_VZ = 32\n"
"uint16 IGNORE_AFX = 64	# Acceleration/Force vector ignore flags\n"
"uint16 IGNORE_AFY = 128\n"
"uint16 IGNORE_AFZ = 256\n"
"uint16 FORCE = 512	# Force in af vector flag\n"
"uint16 IGNORE_YAW = 1024\n"
"uint16 IGNORE_YAW_RATE = 2048\n"
"\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 acceleration_or_force\n"
"float32 yaw\n"
"float32 yaw_rate\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: mavros_msgs/AttitudeTarget\n"
"# Message for SET_ATTITUDE_TARGET\n"
"#\n"
"# Some complex system requires all feautures that mavlink\n"
"# message provide. See issue #402, #418.\n"
"\n"
"std_msgs/Header header\n"
"\n"
"uint8 type_mask\n"
"uint8 IGNORE_ROLL_RATE = 1	# body_rate.x\n"
"uint8 IGNORE_PITCH_RATE = 2	# body_rate.y\n"
"uint8 IGNORE_YAW_RATE = 4	# body_rate.z\n"
"uint8 IGNORE_THRUST = 64\n"
"uint8 IGNORE_ATTITUDE = 128	# orientation field\n"
"\n"
"geometry_msgs/Quaternion orientation\n"
"geometry_msgs/Vector3 body_rate\n"
"float32 thrust\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.source);
      stream.next(m.kind);
      stream.next(m.valid);
      stream.next(m.local);
      stream.next(m.attitude);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlSetpoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_wall_ceiling_control::ControlSetpoint_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "source: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.source);
    s << indent << "kind: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.kind);
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    s << indent << "local: ";
    s << std::endl;
    Printer< ::mavros_msgs::PositionTarget_<ContainerAllocator> >::stream(s, indent + "  ", v.local);
    s << indent << "attitude: ";
    s << std::endl;
    Printer< ::mavros_msgs::AttitudeTarget_<ContainerAllocator> >::stream(s, indent + "  ", v.attitude);
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_WALL_CEILING_CONTROL_MESSAGE_CONTROLSETPOINT_H
