// Generated by gencpp from file px4_wall_ceiling_control/OperatorCommand.msg
// DO NOT EDIT!


#ifndef PX4_WALL_CEILING_CONTROL_MESSAGE_OPERATORCOMMAND_H
#define PX4_WALL_CEILING_CONTROL_MESSAGE_OPERATORCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace px4_wall_ceiling_control
{
template <class ContainerAllocator>
struct OperatorCommand_
{
  typedef OperatorCommand_<ContainerAllocator> Type;

  OperatorCommand_()
    : header()
    , mode(0)
    , enable_control(false)
    , source()
    , reason()  {
    }
  OperatorCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mode(0)
    , enable_control(false)
    , source(_alloc)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _enable_control_type;
  _enable_control_type enable_control;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _source_type;
  _source_type source;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(MODE_MANUAL)
  #undef MODE_MANUAL
#endif
#if defined(_WIN32) && defined(MODE_STANDBY)
  #undef MODE_STANDBY
#endif
#if defined(_WIN32) && defined(MODE_CEILING)
  #undef MODE_CEILING
#endif
#if defined(_WIN32) && defined(MODE_WALL)
  #undef MODE_WALL
#endif
#if defined(_WIN32) && defined(MODE_ABORT)
  #undef MODE_ABORT
#endif

  enum {
    MODE_MANUAL = 0u,
    MODE_STANDBY = 1u,
    MODE_CEILING = 2u,
    MODE_WALL = 3u,
    MODE_ABORT = 4u,
  };


  typedef boost::shared_ptr< ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator> const> ConstPtr;

}; // struct OperatorCommand_

typedef ::px4_wall_ceiling_control::OperatorCommand_<std::allocator<void> > OperatorCommand;

typedef boost::shared_ptr< ::px4_wall_ceiling_control::OperatorCommand > OperatorCommandPtr;
typedef boost::shared_ptr< ::px4_wall_ceiling_control::OperatorCommand const> OperatorCommandConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.mode == rhs.mode &&
    lhs.enable_control == rhs.enable_control &&
    lhs.source == rhs.source &&
    lhs.reason == rhs.reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_wall_ceiling_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e26e5844feffe9808476e201fd10dcc5";
  }

  static const char* value(const ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe26e5844feffe980ULL;
  static const uint64_t static_value2 = 0x8476e201fd10dcc5ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_wall_ceiling_control/OperatorCommand";
  }

  static const char* value(const ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 MODE_MANUAL=0\n"
"uint8 MODE_STANDBY=1\n"
"uint8 MODE_CEILING=2\n"
"uint8 MODE_WALL=3\n"
"uint8 MODE_ABORT=4\n"
"\n"
"uint8 mode\n"
"bool enable_control\n"
"string source\n"
"string reason\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mode);
      stream.next(m.enable_control);
      stream.next(m.source);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OperatorCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_wall_ceiling_control::OperatorCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "enable_control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_control);
    s << indent << "source: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.source);
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_WALL_CEILING_CONTROL_MESSAGE_OPERATORCOMMAND_H
