// Generated by gencpp from file px4_wall_ceiling_control/SensorHealth.msg
// DO NOT EDIT!


#ifndef PX4_WALL_CEILING_CONTROL_MESSAGE_SENSORHEALTH_H
#define PX4_WALL_CEILING_CONTROL_MESSAGE_SENSORHEALTH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace px4_wall_ceiling_control
{
template <class ContainerAllocator>
struct SensorHealth_
{
  typedef SensorHealth_<ContainerAllocator> Type;

  SensorHealth_()
    : header()
    , ceiling_valid(false)
    , front_valid(false)
    , ceiling_age_s(0.0)
    , front_age_s(0.0)
    , ceiling_sequence(0)
    , front_sequence(0)
    , ceiling_invalid_count(0)
    , front_invalid_count(0)  {
    }
  SensorHealth_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ceiling_valid(false)
    , front_valid(false)
    , ceiling_age_s(0.0)
    , front_age_s(0.0)
    , ceiling_sequence(0)
    , front_sequence(0)
    , ceiling_invalid_count(0)
    , front_invalid_count(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _ceiling_valid_type;
  _ceiling_valid_type ceiling_valid;

   typedef uint8_t _front_valid_type;
  _front_valid_type front_valid;

   typedef float _ceiling_age_s_type;
  _ceiling_age_s_type ceiling_age_s;

   typedef float _front_age_s_type;
  _front_age_s_type front_age_s;

   typedef uint32_t _ceiling_sequence_type;
  _ceiling_sequence_type ceiling_sequence;

   typedef uint32_t _front_sequence_type;
  _front_sequence_type front_sequence;

   typedef uint32_t _ceiling_invalid_count_type;
  _ceiling_invalid_count_type ceiling_invalid_count;

   typedef uint32_t _front_invalid_count_type;
  _front_invalid_count_type front_invalid_count;





  typedef boost::shared_ptr< ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator> const> ConstPtr;

}; // struct SensorHealth_

typedef ::px4_wall_ceiling_control::SensorHealth_<std::allocator<void> > SensorHealth;

typedef boost::shared_ptr< ::px4_wall_ceiling_control::SensorHealth > SensorHealthPtr;
typedef boost::shared_ptr< ::px4_wall_ceiling_control::SensorHealth const> SensorHealthConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ceiling_valid == rhs.ceiling_valid &&
    lhs.front_valid == rhs.front_valid &&
    lhs.ceiling_age_s == rhs.ceiling_age_s &&
    lhs.front_age_s == rhs.front_age_s &&
    lhs.ceiling_sequence == rhs.ceiling_sequence &&
    lhs.front_sequence == rhs.front_sequence &&
    lhs.ceiling_invalid_count == rhs.ceiling_invalid_count &&
    lhs.front_invalid_count == rhs.front_invalid_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_wall_ceiling_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "890f31b2daff364b0bc989c3503517bf";
  }

  static const char* value(const ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x890f31b2daff364bULL;
  static const uint64_t static_value2 = 0x0bc989c3503517bfULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_wall_ceiling_control/SensorHealth";
  }

  static const char* value(const ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"bool ceiling_valid\n"
"bool front_valid\n"
"\n"
"# Age of the last valid sample as measured at this node. Infinity means that\n"
"# no valid sample has been received since startup.\n"
"float32 ceiling_age_s\n"
"float32 front_age_s\n"
"\n"
"# Monotonic counters allow consumers and tests to distinguish real samples\n"
"# from repeated status publications.\n"
"uint32 ceiling_sequence\n"
"uint32 front_sequence\n"
"uint32 ceiling_invalid_count\n"
"uint32 front_invalid_count\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ceiling_valid);
      stream.next(m.front_valid);
      stream.next(m.ceiling_age_s);
      stream.next(m.front_age_s);
      stream.next(m.ceiling_sequence);
      stream.next(m.front_sequence);
      stream.next(m.ceiling_invalid_count);
      stream.next(m.front_invalid_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorHealth_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_wall_ceiling_control::SensorHealth_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ceiling_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ceiling_valid);
    s << indent << "front_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.front_valid);
    s << indent << "ceiling_age_s: ";
    Printer<float>::stream(s, indent + "  ", v.ceiling_age_s);
    s << indent << "front_age_s: ";
    Printer<float>::stream(s, indent + "  ", v.front_age_s);
    s << indent << "ceiling_sequence: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.ceiling_sequence);
    s << indent << "front_sequence: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.front_sequence);
    s << indent << "ceiling_invalid_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.ceiling_invalid_count);
    s << indent << "front_invalid_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.front_invalid_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_WALL_CEILING_CONTROL_MESSAGE_SENSORHEALTH_H
