// Generated by gencpp from file px4_wall_ceiling_control/SupervisorState.msg
// DO NOT EDIT!


#ifndef PX4_WALL_CEILING_CONTROL_MESSAGE_SUPERVISORSTATE_H
#define PX4_WALL_CEILING_CONTROL_MESSAGE_SUPERVISORSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace px4_wall_ceiling_control
{
template <class ContainerAllocator>
struct SupervisorState_
{
  typedef SupervisorState_<ContainerAllocator> Type;

  SupervisorState_()
    : header()
    , state(0)
    , active_mode(0)
    , setpoint_stream_allowed(false)
    , motion_allowed(false)
    , mavros_connected(false)
    , armed(false)
    , offboard(false)
    , operator_fresh(false)
    , odom_fresh(false)
    , ceiling_range_fresh(false)
    , wall_range_fresh(false)
    , fault_mask(0)
    , reason()  {
    }
  SupervisorState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)
    , active_mode(0)
    , setpoint_stream_allowed(false)
    , motion_allowed(false)
    , mavros_connected(false)
    , armed(false)
    , offboard(false)
    , operator_fresh(false)
    , odom_fresh(false)
    , ceiling_range_fresh(false)
    , wall_range_fresh(false)
    , fault_mask(0)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _state_type;
  _state_type state;

   typedef uint8_t _active_mode_type;
  _active_mode_type active_mode;

   typedef uint8_t _setpoint_stream_allowed_type;
  _setpoint_stream_allowed_type setpoint_stream_allowed;

   typedef uint8_t _motion_allowed_type;
  _motion_allowed_type motion_allowed;

   typedef uint8_t _mavros_connected_type;
  _mavros_connected_type mavros_connected;

   typedef uint8_t _armed_type;
  _armed_type armed;

   typedef uint8_t _offboard_type;
  _offboard_type offboard;

   typedef uint8_t _operator_fresh_type;
  _operator_fresh_type operator_fresh;

   typedef uint8_t _odom_fresh_type;
  _odom_fresh_type odom_fresh;

   typedef uint8_t _ceiling_range_fresh_type;
  _ceiling_range_fresh_type ceiling_range_fresh;

   typedef uint8_t _wall_range_fresh_type;
  _wall_range_fresh_type wall_range_fresh;

   typedef uint32_t _fault_mask_type;
  _fault_mask_type fault_mask;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STATE_WAIT_LINK)
  #undef STATE_WAIT_LINK
#endif
#if defined(_WIN32) && defined(STATE_MANUAL)
  #undef STATE_MANUAL
#endif
#if defined(_WIN32) && defined(STATE_STANDBY)
  #undef STATE_STANDBY
#endif
#if defined(_WIN32) && defined(STATE_PRESTREAM)
  #undef STATE_PRESTREAM
#endif
#if defined(_WIN32) && defined(STATE_CEILING_ACTIVE)
  #undef STATE_CEILING_ACTIVE
#endif
#if defined(_WIN32) && defined(STATE_WALL_ACTIVE)
  #undef STATE_WALL_ACTIVE
#endif
#if defined(_WIN32) && defined(STATE_FAULT)
  #undef STATE_FAULT
#endif
#if defined(_WIN32) && defined(MODE_NONE)
  #undef MODE_NONE
#endif
#if defined(_WIN32) && defined(MODE_CEILING)
  #undef MODE_CEILING
#endif
#if defined(_WIN32) && defined(MODE_WALL)
  #undef MODE_WALL
#endif
#if defined(_WIN32) && defined(FAULT_NONE)
  #undef FAULT_NONE
#endif
#if defined(_WIN32) && defined(FAULT_MAVROS)
  #undef FAULT_MAVROS
#endif
#if defined(_WIN32) && defined(FAULT_OPERATOR)
  #undef FAULT_OPERATOR
#endif
#if defined(_WIN32) && defined(FAULT_ODOMETRY)
  #undef FAULT_ODOMETRY
#endif
#if defined(_WIN32) && defined(FAULT_CEILING_RANGE)
  #undef FAULT_CEILING_RANGE
#endif
#if defined(_WIN32) && defined(FAULT_WALL_RANGE)
  #undef FAULT_WALL_RANGE
#endif
#if defined(_WIN32) && defined(FAULT_UNKNOWN_MODE)
  #undef FAULT_UNKNOWN_MODE
#endif

  enum {
    STATE_WAIT_LINK = 0u,
    STATE_MANUAL = 1u,
    STATE_STANDBY = 2u,
    STATE_PRESTREAM = 3u,
    STATE_CEILING_ACTIVE = 4u,
    STATE_WALL_ACTIVE = 5u,
    STATE_FAULT = 6u,
    MODE_NONE = 0u,
    MODE_CEILING = 1u,
    MODE_WALL = 2u,
    FAULT_NONE = 0u,
    FAULT_MAVROS = 1u,
    FAULT_OPERATOR = 2u,
    FAULT_ODOMETRY = 4u,
    FAULT_CEILING_RANGE = 8u,
    FAULT_WALL_RANGE = 16u,
    FAULT_UNKNOWN_MODE = 32u,
  };


  typedef boost::shared_ptr< ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator> const> ConstPtr;

}; // struct SupervisorState_

typedef ::px4_wall_ceiling_control::SupervisorState_<std::allocator<void> > SupervisorState;

typedef boost::shared_ptr< ::px4_wall_ceiling_control::SupervisorState > SupervisorStatePtr;
typedef boost::shared_ptr< ::px4_wall_ceiling_control::SupervisorState const> SupervisorStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state &&
    lhs.active_mode == rhs.active_mode &&
    lhs.setpoint_stream_allowed == rhs.setpoint_stream_allowed &&
    lhs.motion_allowed == rhs.motion_allowed &&
    lhs.mavros_connected == rhs.mavros_connected &&
    lhs.armed == rhs.armed &&
    lhs.offboard == rhs.offboard &&
    lhs.operator_fresh == rhs.operator_fresh &&
    lhs.odom_fresh == rhs.odom_fresh &&
    lhs.ceiling_range_fresh == rhs.ceiling_range_fresh &&
    lhs.wall_range_fresh == rhs.wall_range_fresh &&
    lhs.fault_mask == rhs.fault_mask &&
    lhs.reason == rhs.reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator1> & lhs, const ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_wall_ceiling_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ec3406c7c8a31f63daae31442cabb75";
  }

  static const char* value(const ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ec3406c7c8a31f6ULL;
  static const uint64_t static_value2 = 0x3daae31442cabb75ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_wall_ceiling_control/SupervisorState";
  }

  static const char* value(const ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 STATE_WAIT_LINK=0\n"
"uint8 STATE_MANUAL=1\n"
"uint8 STATE_STANDBY=2\n"
"uint8 STATE_PRESTREAM=3\n"
"uint8 STATE_CEILING_ACTIVE=4\n"
"uint8 STATE_WALL_ACTIVE=5\n"
"uint8 STATE_FAULT=6\n"
"\n"
"uint8 MODE_NONE=0\n"
"uint8 MODE_CEILING=1\n"
"uint8 MODE_WALL=2\n"
"\n"
"uint32 FAULT_NONE=0\n"
"uint32 FAULT_MAVROS=1\n"
"uint32 FAULT_OPERATOR=2\n"
"uint32 FAULT_ODOMETRY=4\n"
"uint32 FAULT_CEILING_RANGE=8\n"
"uint32 FAULT_WALL_RANGE=16\n"
"uint32 FAULT_UNKNOWN_MODE=32\n"
"\n"
"uint8 state\n"
"uint8 active_mode\n"
"bool setpoint_stream_allowed\n"
"bool motion_allowed\n"
"bool mavros_connected\n"
"bool armed\n"
"bool offboard\n"
"bool operator_fresh\n"
"bool odom_fresh\n"
"bool ceiling_range_fresh\n"
"bool wall_range_fresh\n"
"uint32 fault_mask\n"
"string reason\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.active_mode);
      stream.next(m.setpoint_stream_allowed);
      stream.next(m.motion_allowed);
      stream.next(m.mavros_connected);
      stream.next(m.armed);
      stream.next(m.offboard);
      stream.next(m.operator_fresh);
      stream.next(m.odom_fresh);
      stream.next(m.ceiling_range_fresh);
      stream.next(m.wall_range_fresh);
      stream.next(m.fault_mask);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SupervisorState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_wall_ceiling_control::SupervisorState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "active_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.active_mode);
    s << indent << "setpoint_stream_allowed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.setpoint_stream_allowed);
    s << indent << "motion_allowed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motion_allowed);
    s << indent << "mavros_connected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mavros_connected);
    s << indent << "armed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.armed);
    s << indent << "offboard: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.offboard);
    s << indent << "operator_fresh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.operator_fresh);
    s << indent << "odom_fresh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.odom_fresh);
    s << indent << "ceiling_range_fresh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ceiling_range_fresh);
    s << indent << "wall_range_fresh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wall_range_fresh);
    s << indent << "fault_mask: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.fault_mask);
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_WALL_CEILING_CONTROL_MESSAGE_SUPERVISORSTATE_H
